// Code generated by ent, DO NOT EDIT.

package remindtaskinventoryitem

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldID, id))
}

// TaskChannelID applies equality check predicate on the "task_channel_id" field. It's identical to TaskChannelIDEQ.
func TaskChannelID(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldTaskChannelID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldTaskID, v))
}

// InventoryChannelID applies equality check predicate on the "inventory_channel_id" field. It's identical to InventoryChannelIDEQ.
func InventoryChannelID(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldInventoryChannelID, v))
}

// InventoryID applies equality check predicate on the "inventory_id" field. It's identical to InventoryIDEQ.
func InventoryID(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldInventoryID, v))
}

// Consume applies equality check predicate on the "consume" field. It's identical to ConsumeEQ.
func Consume(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldConsume, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldPosition, v))
}

// TaskChannelIDEQ applies the EQ predicate on the "task_channel_id" field.
func TaskChannelIDEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldTaskChannelID, v))
}

// TaskChannelIDNEQ applies the NEQ predicate on the "task_channel_id" field.
func TaskChannelIDNEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldTaskChannelID, v))
}

// TaskChannelIDIn applies the In predicate on the "task_channel_id" field.
func TaskChannelIDIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldTaskChannelID, vs...))
}

// TaskChannelIDNotIn applies the NotIn predicate on the "task_channel_id" field.
func TaskChannelIDNotIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldTaskChannelID, vs...))
}

// TaskChannelIDGT applies the GT predicate on the "task_channel_id" field.
func TaskChannelIDGT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldTaskChannelID, v))
}

// TaskChannelIDGTE applies the GTE predicate on the "task_channel_id" field.
func TaskChannelIDGTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldTaskChannelID, v))
}

// TaskChannelIDLT applies the LT predicate on the "task_channel_id" field.
func TaskChannelIDLT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldTaskChannelID, v))
}

// TaskChannelIDLTE applies the LTE predicate on the "task_channel_id" field.
func TaskChannelIDLTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldTaskChannelID, v))
}

// TaskChannelIDContains applies the Contains predicate on the "task_channel_id" field.
func TaskChannelIDContains(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContains(FieldTaskChannelID, v))
}

// TaskChannelIDHasPrefix applies the HasPrefix predicate on the "task_channel_id" field.
func TaskChannelIDHasPrefix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasPrefix(FieldTaskChannelID, v))
}

// TaskChannelIDHasSuffix applies the HasSuffix predicate on the "task_channel_id" field.
func TaskChannelIDHasSuffix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasSuffix(FieldTaskChannelID, v))
}

// TaskChannelIDEqualFold applies the EqualFold predicate on the "task_channel_id" field.
func TaskChannelIDEqualFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEqualFold(FieldTaskChannelID, v))
}

// TaskChannelIDContainsFold applies the ContainsFold predicate on the "task_channel_id" field.
func TaskChannelIDContainsFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContainsFold(FieldTaskChannelID, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContainsFold(FieldTaskID, v))
}

// InventoryChannelIDEQ applies the EQ predicate on the "inventory_channel_id" field.
func InventoryChannelIDEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldInventoryChannelID, v))
}

// InventoryChannelIDNEQ applies the NEQ predicate on the "inventory_channel_id" field.
func InventoryChannelIDNEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldInventoryChannelID, v))
}

// InventoryChannelIDIn applies the In predicate on the "inventory_channel_id" field.
func InventoryChannelIDIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldInventoryChannelID, vs...))
}

// InventoryChannelIDNotIn applies the NotIn predicate on the "inventory_channel_id" field.
func InventoryChannelIDNotIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldInventoryChannelID, vs...))
}

// InventoryChannelIDGT applies the GT predicate on the "inventory_channel_id" field.
func InventoryChannelIDGT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldInventoryChannelID, v))
}

// InventoryChannelIDGTE applies the GTE predicate on the "inventory_channel_id" field.
func InventoryChannelIDGTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldInventoryChannelID, v))
}

// InventoryChannelIDLT applies the LT predicate on the "inventory_channel_id" field.
func InventoryChannelIDLT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldInventoryChannelID, v))
}

// InventoryChannelIDLTE applies the LTE predicate on the "inventory_channel_id" field.
func InventoryChannelIDLTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldInventoryChannelID, v))
}

// InventoryChannelIDContains applies the Contains predicate on the "inventory_channel_id" field.
func InventoryChannelIDContains(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContains(FieldInventoryChannelID, v))
}

// InventoryChannelIDHasPrefix applies the HasPrefix predicate on the "inventory_channel_id" field.
func InventoryChannelIDHasPrefix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasPrefix(FieldInventoryChannelID, v))
}

// InventoryChannelIDHasSuffix applies the HasSuffix predicate on the "inventory_channel_id" field.
func InventoryChannelIDHasSuffix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasSuffix(FieldInventoryChannelID, v))
}

// InventoryChannelIDEqualFold applies the EqualFold predicate on the "inventory_channel_id" field.
func InventoryChannelIDEqualFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEqualFold(FieldInventoryChannelID, v))
}

// InventoryChannelIDContainsFold applies the ContainsFold predicate on the "inventory_channel_id" field.
func InventoryChannelIDContainsFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContainsFold(FieldInventoryChannelID, v))
}

// InventoryIDEQ applies the EQ predicate on the "inventory_id" field.
func InventoryIDEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldInventoryID, v))
}

// InventoryIDNEQ applies the NEQ predicate on the "inventory_id" field.
func InventoryIDNEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldInventoryID, v))
}

// InventoryIDIn applies the In predicate on the "inventory_id" field.
func InventoryIDIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldInventoryID, vs...))
}

// InventoryIDNotIn applies the NotIn predicate on the "inventory_id" field.
func InventoryIDNotIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldInventoryID, vs...))
}

// InventoryIDGT applies the GT predicate on the "inventory_id" field.
func InventoryIDGT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldInventoryID, v))
}

// InventoryIDGTE applies the GTE predicate on the "inventory_id" field.
func InventoryIDGTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldInventoryID, v))
}

// InventoryIDLT applies the LT predicate on the "inventory_id" field.
func InventoryIDLT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldInventoryID, v))
}

// InventoryIDLTE applies the LTE predicate on the "inventory_id" field.
func InventoryIDLTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldInventoryID, v))
}

// InventoryIDContains applies the Contains predicate on the "inventory_id" field.
func InventoryIDContains(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContains(FieldInventoryID, v))
}

// InventoryIDHasPrefix applies the HasPrefix predicate on the "inventory_id" field.
func InventoryIDHasPrefix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasPrefix(FieldInventoryID, v))
}

// InventoryIDHasSuffix applies the HasSuffix predicate on the "inventory_id" field.
func InventoryIDHasSuffix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasSuffix(FieldInventoryID, v))
}

// InventoryIDEqualFold applies the EqualFold predicate on the "inventory_id" field.
func InventoryIDEqualFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEqualFold(FieldInventoryID, v))
}

// InventoryIDContainsFold applies the ContainsFold predicate on the "inventory_id" field.
func InventoryIDContainsFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContainsFold(FieldInventoryID, v))
}

// ConsumeEQ applies the EQ predicate on the "consume" field.
func ConsumeEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldConsume, v))
}

// ConsumeNEQ applies the NEQ predicate on the "consume" field.
func ConsumeNEQ(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldConsume, v))
}

// ConsumeIn applies the In predicate on the "consume" field.
func ConsumeIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldConsume, vs...))
}

// ConsumeNotIn applies the NotIn predicate on the "consume" field.
func ConsumeNotIn(vs ...string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldConsume, vs...))
}

// ConsumeGT applies the GT predicate on the "consume" field.
func ConsumeGT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldConsume, v))
}

// ConsumeGTE applies the GTE predicate on the "consume" field.
func ConsumeGTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldConsume, v))
}

// ConsumeLT applies the LT predicate on the "consume" field.
func ConsumeLT(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldConsume, v))
}

// ConsumeLTE applies the LTE predicate on the "consume" field.
func ConsumeLTE(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldConsume, v))
}

// ConsumeContains applies the Contains predicate on the "consume" field.
func ConsumeContains(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContains(FieldConsume, v))
}

// ConsumeHasPrefix applies the HasPrefix predicate on the "consume" field.
func ConsumeHasPrefix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasPrefix(FieldConsume, v))
}

// ConsumeHasSuffix applies the HasSuffix predicate on the "consume" field.
func ConsumeHasSuffix(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldHasSuffix(FieldConsume, v))
}

// ConsumeEqualFold applies the EqualFold predicate on the "consume" field.
func ConsumeEqualFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEqualFold(FieldConsume, v))
}

// ConsumeContainsFold applies the ContainsFold predicate on the "consume" field.
func ConsumeContainsFold(v string) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldContainsFold(FieldConsume, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.FieldLTE(FieldPosition, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RemindTaskInventoryItem) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RemindTaskInventoryItem) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RemindTaskInventoryItem) predicate.RemindTaskInventoryItem {
	return predicate.RemindTaskInventoryItem(sql.NotPredicates(p))
}
