// Code generated by ent, DO NOT EDIT.

package outputdispatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldTaskID, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldAttempt, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldNonce, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldFinishedAt, v))
}

// Outcome applies equality check predicate on the "outcome" field. It's identical to OutcomeEQ.
func Outcome(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldOutcome, v))
}

// DiscordMessageID applies equality check predicate on the "discord_message_id" field. It's identical to DiscordMessageIDEQ.
func DiscordMessageID(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldDiscordMessageID, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v uuid.UUID) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldTaskID, v))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldAttempt, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldNonce, v))
}

// NonceContains applies the Contains predicate on the "nonce" field.
func NonceContains(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldContains(FieldNonce, v))
}

// NonceHasPrefix applies the HasPrefix predicate on the "nonce" field.
func NonceHasPrefix(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldHasPrefix(FieldNonce, v))
}

// NonceHasSuffix applies the HasSuffix predicate on the "nonce" field.
func NonceHasSuffix(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldHasSuffix(FieldNonce, v))
}

// NonceEqualFold applies the EqualFold predicate on the "nonce" field.
func NonceEqualFold(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEqualFold(FieldNonce, v))
}

// NonceContainsFold applies the ContainsFold predicate on the "nonce" field.
func NonceContainsFold(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldContainsFold(FieldNonce, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotNull(FieldFinishedAt))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeGT applies the GT predicate on the "outcome" field.
func OutcomeGT(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldOutcome, v))
}

// OutcomeGTE applies the GTE predicate on the "outcome" field.
func OutcomeGTE(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldOutcome, v))
}

// OutcomeLT applies the LT predicate on the "outcome" field.
func OutcomeLT(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldOutcome, v))
}

// OutcomeLTE applies the LTE predicate on the "outcome" field.
func OutcomeLTE(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldOutcome, v))
}

// OutcomeContains applies the Contains predicate on the "outcome" field.
func OutcomeContains(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldContains(FieldOutcome, v))
}

// OutcomeHasPrefix applies the HasPrefix predicate on the "outcome" field.
func OutcomeHasPrefix(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldHasPrefix(FieldOutcome, v))
}

// OutcomeHasSuffix applies the HasSuffix predicate on the "outcome" field.
func OutcomeHasSuffix(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldHasSuffix(FieldOutcome, v))
}

// OutcomeEqualFold applies the EqualFold predicate on the "outcome" field.
func OutcomeEqualFold(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEqualFold(FieldOutcome, v))
}

// OutcomeContainsFold applies the ContainsFold predicate on the "outcome" field.
func OutcomeContainsFold(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldContainsFold(FieldOutcome, v))
}

// DiscordMessageIDEQ applies the EQ predicate on the "discord_message_id" field.
func DiscordMessageIDEQ(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEQ(FieldDiscordMessageID, v))
}

// DiscordMessageIDNEQ applies the NEQ predicate on the "discord_message_id" field.
func DiscordMessageIDNEQ(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNEQ(FieldDiscordMessageID, v))
}

// DiscordMessageIDIn applies the In predicate on the "discord_message_id" field.
func DiscordMessageIDIn(vs ...string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldIn(FieldDiscordMessageID, vs...))
}

// DiscordMessageIDNotIn applies the NotIn predicate on the "discord_message_id" field.
func DiscordMessageIDNotIn(vs ...string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldNotIn(FieldDiscordMessageID, vs...))
}

// DiscordMessageIDGT applies the GT predicate on the "discord_message_id" field.
func DiscordMessageIDGT(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGT(FieldDiscordMessageID, v))
}

// DiscordMessageIDGTE applies the GTE predicate on the "discord_message_id" field.
func DiscordMessageIDGTE(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldGTE(FieldDiscordMessageID, v))
}

// DiscordMessageIDLT applies the LT predicate on the "discord_message_id" field.
func DiscordMessageIDLT(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLT(FieldDiscordMessageID, v))
}

// DiscordMessageIDLTE applies the LTE predicate on the "discord_message_id" field.
func DiscordMessageIDLTE(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldLTE(FieldDiscordMessageID, v))
}

// DiscordMessageIDContains applies the Contains predicate on the "discord_message_id" field.
func DiscordMessageIDContains(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldContains(FieldDiscordMessageID, v))
}

// DiscordMessageIDHasPrefix applies the HasPrefix predicate on the "discord_message_id" field.
func DiscordMessageIDHasPrefix(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldHasPrefix(FieldDiscordMessageID, v))
}

// DiscordMessageIDHasSuffix applies the HasSuffix predicate on the "discord_message_id" field.
func DiscordMessageIDHasSuffix(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldHasSuffix(FieldDiscordMessageID, v))
}

// DiscordMessageIDEqualFold applies the EqualFold predicate on the "discord_message_id" field.
func DiscordMessageIDEqualFold(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldEqualFold(FieldDiscordMessageID, v))
}

// DiscordMessageIDContainsFold applies the ContainsFold predicate on the "discord_message_id" field.
func DiscordMessageIDContainsFold(v string) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.FieldContainsFold(FieldDiscordMessageID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OutputDispatch) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OutputDispatch) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OutputDispatch) predicate.OutputDispatch {
	return predicate.OutputDispatch(sql.NotPredicates(p))
}
