// Code generated by ent, DO NOT EDIT.

package listchannel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the listchannel type in the database.
	Label = "list_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "channel_id"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldListTitle holds the string denoting the list_title field in the database.
	FieldListTitle = "list_title"
	// FieldOperationLogThreadID holds the string denoting the operation_log_thread_id field in the database.
	FieldOperationLogThreadID = "operation_log_thread_id"
	// FieldDefaultCategory holds the string denoting the default_category field in the database.
	FieldDefaultCategory = "default_category"
	// FieldEditVersion holds the string denoting the edit_version field in the database.
	FieldEditVersion = "edit_version"
	// Table holds the table name of the listchannel in the database.
	Table = "list_channels"
)

// Columns holds all SQL columns for listchannel fields.
var Columns = []string{
	FieldID,
	FieldMessageID,
	FieldListTitle,
	FieldOperationLogThreadID,
	FieldDefaultCategory,
	FieldEditVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDefaultCategory holds the default value on creation for the "default_category" field.
	DefaultDefaultCategory string
	// DefaultEditVersion holds the default value on creation for the "edit_version" field.
	DefaultEditVersion int64
)

// OrderOption defines the ordering options for the ListChannel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByListTitle orders the results by the list_title field.
func ByListTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListTitle, opts...).ToFunc()
}

// ByOperationLogThreadID orders the results by the operation_log_thread_id field.
func ByOperationLogThreadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationLogThreadID, opts...).ToFunc()
}

// ByDefaultCategory orders the results by the default_category field.
func ByDefaultCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultCategory, opts...).ToFunc()
}

// ByEditVersion orders the results by the edit_version field.
func ByEditVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEditVersion, opts...).ToFunc()
}
