// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// InventoryChannel is the predicate function for inventorychannel builders.
type InventoryChannel func(*sql.Selector)

// InventoryItem is the predicate function for inventoryitem builders.
type InventoryItem func(*sql.Selector)

// ListChannel is the predicate function for listchannel builders.
type ListChannel func(*sql.Selector)

// ListItem is the predicate function for listitem builders.
type ListItem func(*sql.Selector)

// RemindChannel is the predicate function for remindchannel builders.
type RemindChannel func(*sql.Selector)

// RemindTask is the predicate function for remindtask builders.
type RemindTask func(*sql.Selector)

// RemindTaskInventoryItem is the predicate function for remindtaskinventoryitem builders.
type RemindTaskInventoryItem func(*sql.Selector)
