// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InventoryChannelsColumns holds the columns for the "inventory_channels" table.
	InventoryChannelsColumns = []*schema.Column{
		{Name: "channel_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString, Nullable: true},
		{Name: "list_title", Type: field.TypeString},
		{Name: "operation_log_thread_id", Type: field.TypeString, Nullable: true},
		{Name: "default_category", Type: field.TypeString, Default: "その他"},
	}
	// InventoryChannelsTable holds the schema information for the "inventory_channels" table.
	InventoryChannelsTable = &schema.Table{
		Name:       "inventory_channels",
		Columns:    InventoryChannelsColumns,
		PrimaryKey: []*schema.Column{InventoryChannelsColumns[0]},
	}
	// InventoryItemsColumns holds the columns for the "inventory_items" table.
	InventoryItemsColumns = []*schema.Column{
		{Name: "entity_id", Type: field.TypeUUID},
		{Name: "id", Type: field.TypeString},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "stock", Type: field.TypeString, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "position", Type: field.TypeInt},
	}
	// InventoryItemsTable holds the schema information for the "inventory_items" table.
	InventoryItemsTable = &schema.Table{
		Name:       "inventory_items",
		Columns:    InventoryItemsColumns,
		PrimaryKey: []*schema.Column{InventoryItemsColumns[0]},
	}
	// ListChannelsColumns holds the columns for the "list_channels" table.
	ListChannelsColumns = []*schema.Column{
		{Name: "channel_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString, Nullable: true},
		{Name: "list_title", Type: field.TypeString},
		{Name: "operation_log_thread_id", Type: field.TypeString, Nullable: true},
		{Name: "default_category", Type: field.TypeString, Default: "その他"},
		{Name: "edit_version", Type: field.TypeInt64, Default: 0},
	}
	// ListChannelsTable holds the schema information for the "list_channels" table.
	ListChannelsTable = &schema.Table{
		Name:       "list_channels",
		Columns:    ListChannelsColumns,
		PrimaryKey: []*schema.Column{ListChannelsColumns[0]},
	}
	// ListItemsColumns holds the columns for the "list_items" table.
	ListItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "until", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "is_completed", Type: field.TypeBool, Default: false},
		{Name: "last_notified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "position", Type: field.TypeInt},
	}
	// ListItemsTable holds the schema information for the "list_items" table.
	ListItemsTable = &schema.Table{
		Name:       "list_items",
		Columns:    ListItemsColumns,
		PrimaryKey: []*schema.Column{ListItemsColumns[0]},
	}
	// RemindChannelsColumns holds the columns for the "remind_channels" table.
	RemindChannelsColumns = []*schema.Column{
		{Name: "channel_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString, Nullable: true},
		{Name: "list_title", Type: field.TypeString},
		{Name: "operation_log_thread_id", Type: field.TypeString, Nullable: true},
		{Name: "remind_notice_thread_id", Type: field.TypeString, Nullable: true},
		{Name: "remind_notice_message_id", Type: field.TypeString, Nullable: true},
		{Name: "linked_inventory_channel_id", Type: field.TypeString, Nullable: true},
	}
	// RemindChannelsTable holds the schema information for the "remind_channels" table.
	RemindChannelsTable = &schema.Table{
		Name:       "remind_channels",
		Columns:    RemindChannelsColumns,
		PrimaryKey: []*schema.Column{RemindChannelsColumns[0]},
	}
	// RemindTasksColumns holds the columns for the "remind_tasks" table.
	RemindTasksColumns = []*schema.Column{
		{Name: "entity_id", Type: field.TypeUUID},
		{Name: "id", Type: field.TypeString},
		{Name: "channel_id", Type: field.TypeString},
		{Name: "message_id", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "interval_days", Type: field.TypeInt},
		{Name: "time_of_day", Type: field.TypeString, SchemaType: map[string]string{"postgres": "time(0)"}},
		{Name: "remind_before_minutes", Type: field.TypeInt},
		{Name: "start_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "next_due_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "last_done_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "last_remind_due_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "last_overdue_notified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz(3)"}},
		{Name: "overdue_notify_count", Type: field.TypeInt, Default: 0},
		{Name: "overdue_notify_limit", Type: field.TypeInt, Nullable: true},
		{Name: "is_paused", Type: field.TypeBool, Default: false},
		{Name: "revision", Type: field.TypeInt64, Default: 0},
		{Name: "position", Type: field.TypeInt},
	}
	// RemindTasksTable holds the schema information for the "remind_tasks" table.
	RemindTasksTable = &schema.Table{
		Name:       "remind_tasks",
		Columns:    RemindTasksColumns,
		PrimaryKey: []*schema.Column{RemindTasksColumns[0]},
	}
	// RemindTaskInventoryItemsColumns holds the columns for the "remind_task_inventory_items" table.
	RemindTaskInventoryItemsColumns = []*schema.Column{
		{Name: "entity_id", Type: field.TypeUUID},
		{Name: "task_channel_id", Type: field.TypeString},
		{Name: "task_id", Type: field.TypeString},
		{Name: "inventory_channel_id", Type: field.TypeString},
		{Name: "inventory_id", Type: field.TypeString},
		{Name: "consume", Type: field.TypeString, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "position", Type: field.TypeInt},
	}
	// RemindTaskInventoryItemsTable holds the schema information for the "remind_task_inventory_items" table.
	RemindTaskInventoryItemsTable = &schema.Table{
		Name:       "remind_task_inventory_items",
		Columns:    RemindTaskInventoryItemsColumns,
		PrimaryKey: []*schema.Column{RemindTaskInventoryItemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InventoryChannelsTable,
		InventoryItemsTable,
		ListChannelsTable,
		ListItemsTable,
		RemindChannelsTable,
		RemindTasksTable,
		RemindTaskInventoryItemsTable,
	}
)

func init() {
	InventoryChannelsTable.Annotation = &entsql.Annotation{
		Table: "inventory_channels",
	}
	InventoryItemsTable.Annotation = &entsql.Annotation{
		Table: "inventory_items",
	}
	ListChannelsTable.Annotation = &entsql.Annotation{
		Table: "list_channels",
	}
	ListItemsTable.Annotation = &entsql.Annotation{
		Table: "list_items",
	}
	RemindChannelsTable.Annotation = &entsql.Annotation{
		Table: "remind_channels",
	}
	RemindTasksTable.Annotation = &entsql.Annotation{
		Table: "remind_tasks",
	}
	RemindTaskInventoryItemsTable.Annotation = &entsql.Annotation{
		Table: "remind_task_inventory_items",
	}
}
