// Code generated by ent, DO NOT EDIT.

package nurserymenu

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the nurserymenu type in the database.
	Label = "nursery_menu"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMenuDate holds the string denoting the menu_date field in the database.
	FieldMenuDate = "menu_date"
	// FieldLunch holds the string denoting the lunch field in the database.
	FieldLunch = "lunch"
	// FieldSnack holds the string denoting the snack field in the database.
	FieldSnack = "snack"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the nurserymenu in the database.
	Table = "nursery_menus"
)

// Columns holds all SQL columns for nurserymenu fields.
var Columns = []string{
	FieldID,
	FieldMenuDate,
	FieldLunch,
	FieldSnack,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLunch holds the default value on creation for the "lunch" field.
	DefaultLunch string
	// DefaultSnack holds the default value on creation for the "snack" field.
	DefaultSnack string
)

// OrderOption defines the ordering options for the NurseryMenu queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMenuDate orders the results by the menu_date field.
func ByMenuDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMenuDate, opts...).ToFunc()
}

// ByLunch orders the results by the lunch field.
func ByLunch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLunch, opts...).ToFunc()
}

// BySnack orders the results by the snack field.
func BySnack(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnack, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
