// Code generated by ent, DO NOT EDIT.

package nurserymenu

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldID, id))
}

// MenuDate applies equality check predicate on the "menu_date" field. It's identical to MenuDateEQ.
func MenuDate(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldMenuDate, v))
}

// Lunch applies equality check predicate on the "lunch" field. It's identical to LunchEQ.
func Lunch(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldLunch, v))
}

// Snack applies equality check predicate on the "snack" field. It's identical to SnackEQ.
func Snack(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldSnack, v))
}

// LunchIngredients applies equality check predicate on the "lunch_ingredients" field. It's identical to LunchIngredientsEQ.
func LunchIngredients(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldLunchIngredients, v))
}

// SnackIngredients applies equality check predicate on the "snack_ingredients" field. It's identical to SnackIngredientsEQ.
func SnackIngredients(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldSnackIngredients, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// MenuDateEQ applies the EQ predicate on the "menu_date" field.
func MenuDateEQ(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldMenuDate, v))
}

// MenuDateNEQ applies the NEQ predicate on the "menu_date" field.
func MenuDateNEQ(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldMenuDate, v))
}

// MenuDateIn applies the In predicate on the "menu_date" field.
func MenuDateIn(vs ...time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldMenuDate, vs...))
}

// MenuDateNotIn applies the NotIn predicate on the "menu_date" field.
func MenuDateNotIn(vs ...time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldMenuDate, vs...))
}

// MenuDateGT applies the GT predicate on the "menu_date" field.
func MenuDateGT(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldMenuDate, v))
}

// MenuDateGTE applies the GTE predicate on the "menu_date" field.
func MenuDateGTE(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldMenuDate, v))
}

// MenuDateLT applies the LT predicate on the "menu_date" field.
func MenuDateLT(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldMenuDate, v))
}

// MenuDateLTE applies the LTE predicate on the "menu_date" field.
func MenuDateLTE(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldMenuDate, v))
}

// LunchEQ applies the EQ predicate on the "lunch" field.
func LunchEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldLunch, v))
}

// LunchNEQ applies the NEQ predicate on the "lunch" field.
func LunchNEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldLunch, v))
}

// LunchIn applies the In predicate on the "lunch" field.
func LunchIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldLunch, vs...))
}

// LunchNotIn applies the NotIn predicate on the "lunch" field.
func LunchNotIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldLunch, vs...))
}

// LunchGT applies the GT predicate on the "lunch" field.
func LunchGT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldLunch, v))
}

// LunchGTE applies the GTE predicate on the "lunch" field.
func LunchGTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldLunch, v))
}

// LunchLT applies the LT predicate on the "lunch" field.
func LunchLT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldLunch, v))
}

// LunchLTE applies the LTE predicate on the "lunch" field.
func LunchLTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldLunch, v))
}

// LunchContains applies the Contains predicate on the "lunch" field.
func LunchContains(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContains(FieldLunch, v))
}

// LunchHasPrefix applies the HasPrefix predicate on the "lunch" field.
func LunchHasPrefix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasPrefix(FieldLunch, v))
}

// LunchHasSuffix applies the HasSuffix predicate on the "lunch" field.
func LunchHasSuffix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasSuffix(FieldLunch, v))
}

// LunchEqualFold applies the EqualFold predicate on the "lunch" field.
func LunchEqualFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEqualFold(FieldLunch, v))
}

// LunchContainsFold applies the ContainsFold predicate on the "lunch" field.
func LunchContainsFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContainsFold(FieldLunch, v))
}

// SnackEQ applies the EQ predicate on the "snack" field.
func SnackEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldSnack, v))
}

// SnackNEQ applies the NEQ predicate on the "snack" field.
func SnackNEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldSnack, v))
}

// SnackIn applies the In predicate on the "snack" field.
func SnackIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldSnack, vs...))
}

// SnackNotIn applies the NotIn predicate on the "snack" field.
func SnackNotIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldSnack, vs...))
}

// SnackGT applies the GT predicate on the "snack" field.
func SnackGT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldSnack, v))
}

// SnackGTE applies the GTE predicate on the "snack" field.
func SnackGTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldSnack, v))
}

// SnackLT applies the LT predicate on the "snack" field.
func SnackLT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldSnack, v))
}

// SnackLTE applies the LTE predicate on the "snack" field.
func SnackLTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldSnack, v))
}

// SnackContains applies the Contains predicate on the "snack" field.
func SnackContains(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContains(FieldSnack, v))
}

// SnackHasPrefix applies the HasPrefix predicate on the "snack" field.
func SnackHasPrefix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasPrefix(FieldSnack, v))
}

// SnackHasSuffix applies the HasSuffix predicate on the "snack" field.
func SnackHasSuffix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasSuffix(FieldSnack, v))
}

// SnackEqualFold applies the EqualFold predicate on the "snack" field.
func SnackEqualFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEqualFold(FieldSnack, v))
}

// SnackContainsFold applies the ContainsFold predicate on the "snack" field.
func SnackContainsFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContainsFold(FieldSnack, v))
}

// LunchIngredientsEQ applies the EQ predicate on the "lunch_ingredients" field.
func LunchIngredientsEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldLunchIngredients, v))
}

// LunchIngredientsNEQ applies the NEQ predicate on the "lunch_ingredients" field.
func LunchIngredientsNEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldLunchIngredients, v))
}

// LunchIngredientsIn applies the In predicate on the "lunch_ingredients" field.
func LunchIngredientsIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldLunchIngredients, vs...))
}

// LunchIngredientsNotIn applies the NotIn predicate on the "lunch_ingredients" field.
func LunchIngredientsNotIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldLunchIngredients, vs...))
}

// LunchIngredientsGT applies the GT predicate on the "lunch_ingredients" field.
func LunchIngredientsGT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldLunchIngredients, v))
}

// LunchIngredientsGTE applies the GTE predicate on the "lunch_ingredients" field.
func LunchIngredientsGTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldLunchIngredients, v))
}

// LunchIngredientsLT applies the LT predicate on the "lunch_ingredients" field.
func LunchIngredientsLT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldLunchIngredients, v))
}

// LunchIngredientsLTE applies the LTE predicate on the "lunch_ingredients" field.
func LunchIngredientsLTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldLunchIngredients, v))
}

// LunchIngredientsContains applies the Contains predicate on the "lunch_ingredients" field.
func LunchIngredientsContains(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContains(FieldLunchIngredients, v))
}

// LunchIngredientsHasPrefix applies the HasPrefix predicate on the "lunch_ingredients" field.
func LunchIngredientsHasPrefix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasPrefix(FieldLunchIngredients, v))
}

// LunchIngredientsHasSuffix applies the HasSuffix predicate on the "lunch_ingredients" field.
func LunchIngredientsHasSuffix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasSuffix(FieldLunchIngredients, v))
}

// LunchIngredientsEqualFold applies the EqualFold predicate on the "lunch_ingredients" field.
func LunchIngredientsEqualFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEqualFold(FieldLunchIngredients, v))
}

// LunchIngredientsContainsFold applies the ContainsFold predicate on the "lunch_ingredients" field.
func LunchIngredientsContainsFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContainsFold(FieldLunchIngredients, v))
}

// SnackIngredientsEQ applies the EQ predicate on the "snack_ingredients" field.
func SnackIngredientsEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldSnackIngredients, v))
}

// SnackIngredientsNEQ applies the NEQ predicate on the "snack_ingredients" field.
func SnackIngredientsNEQ(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldSnackIngredients, v))
}

// SnackIngredientsIn applies the In predicate on the "snack_ingredients" field.
func SnackIngredientsIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldSnackIngredients, vs...))
}

// SnackIngredientsNotIn applies the NotIn predicate on the "snack_ingredients" field.
func SnackIngredientsNotIn(vs ...string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldSnackIngredients, vs...))
}

// SnackIngredientsGT applies the GT predicate on the "snack_ingredients" field.
func SnackIngredientsGT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldSnackIngredients, v))
}

// SnackIngredientsGTE applies the GTE predicate on the "snack_ingredients" field.
func SnackIngredientsGTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldSnackIngredients, v))
}

// SnackIngredientsLT applies the LT predicate on the "snack_ingredients" field.
func SnackIngredientsLT(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldSnackIngredients, v))
}

// SnackIngredientsLTE applies the LTE predicate on the "snack_ingredients" field.
func SnackIngredientsLTE(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldSnackIngredients, v))
}

// SnackIngredientsContains applies the Contains predicate on the "snack_ingredients" field.
func SnackIngredientsContains(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContains(FieldSnackIngredients, v))
}

// SnackIngredientsHasPrefix applies the HasPrefix predicate on the "snack_ingredients" field.
func SnackIngredientsHasPrefix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasPrefix(FieldSnackIngredients, v))
}

// SnackIngredientsHasSuffix applies the HasSuffix predicate on the "snack_ingredients" field.
func SnackIngredientsHasSuffix(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldHasSuffix(FieldSnackIngredients, v))
}

// SnackIngredientsEqualFold applies the EqualFold predicate on the "snack_ingredients" field.
func SnackIngredientsEqualFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEqualFold(FieldSnackIngredients, v))
}

// SnackIngredientsContainsFold applies the ContainsFold predicate on the "snack_ingredients" field.
func SnackIngredientsContainsFold(v string) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldContainsFold(FieldSnackIngredients, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NurseryMenu) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NurseryMenu) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NurseryMenu) predicate.NurseryMenu {
	return predicate.NurseryMenu(sql.NotPredicates(p))
}
