// Code generated by ent, DO NOT EDIT.

package operationrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLTE(FieldID, id))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldChannelID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldActorID, v))
}

// OperationKind applies equality check predicate on the "operation_kind" field. It's identical to OperationKindEQ.
func OperationKind(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldOperationKind, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldSuccess, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldOccurredAt, v))
}

// InteractionID applies equality check predicate on the "interaction_id" field. It's identical to InteractionIDEQ.
func InteractionID(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldInteractionID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channel_id" field.
func ChannelIDContains(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channel_id" field.
func ChannelIDHasPrefix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channel_id" field.
func ChannelIDHasSuffix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channel_id" field.
func ChannelIDEqualFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channel_id" field.
func ChannelIDContainsFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContainsFold(FieldChannelID, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLTE(FieldActorID, v))
}

// ActorIDContains applies the Contains predicate on the "actor_id" field.
func ActorIDContains(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContains(FieldActorID, v))
}

// ActorIDHasPrefix applies the HasPrefix predicate on the "actor_id" field.
func ActorIDHasPrefix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasPrefix(FieldActorID, v))
}

// ActorIDHasSuffix applies the HasSuffix predicate on the "actor_id" field.
func ActorIDHasSuffix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasSuffix(FieldActorID, v))
}

// ActorIDEqualFold applies the EqualFold predicate on the "actor_id" field.
func ActorIDEqualFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEqualFold(FieldActorID, v))
}

// ActorIDContainsFold applies the ContainsFold predicate on the "actor_id" field.
func ActorIDContainsFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContainsFold(FieldActorID, v))
}

// OperationKindEQ applies the EQ predicate on the "operation_kind" field.
func OperationKindEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldOperationKind, v))
}

// OperationKindNEQ applies the NEQ predicate on the "operation_kind" field.
func OperationKindNEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldOperationKind, v))
}

// OperationKindIn applies the In predicate on the "operation_kind" field.
func OperationKindIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIn(FieldOperationKind, vs...))
}

// OperationKindNotIn applies the NotIn predicate on the "operation_kind" field.
func OperationKindNotIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotIn(FieldOperationKind, vs...))
}

// OperationKindGT applies the GT predicate on the "operation_kind" field.
func OperationKindGT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGT(FieldOperationKind, v))
}

// OperationKindGTE applies the GTE predicate on the "operation_kind" field.
func OperationKindGTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGTE(FieldOperationKind, v))
}

// OperationKindLT applies the LT predicate on the "operation_kind" field.
func OperationKindLT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLT(FieldOperationKind, v))
}

// OperationKindLTE applies the LTE predicate on the "operation_kind" field.
func OperationKindLTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLTE(FieldOperationKind, v))
}

// OperationKindContains applies the Contains predicate on the "operation_kind" field.
func OperationKindContains(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContains(FieldOperationKind, v))
}

// OperationKindHasPrefix applies the HasPrefix predicate on the "operation_kind" field.
func OperationKindHasPrefix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasPrefix(FieldOperationKind, v))
}

// OperationKindHasSuffix applies the HasSuffix predicate on the "operation_kind" field.
func OperationKindHasSuffix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasSuffix(FieldOperationKind, v))
}

// OperationKindEqualFold applies the EqualFold predicate on the "operation_kind" field.
func OperationKindEqualFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEqualFold(FieldOperationKind, v))
}

// OperationKindContainsFold applies the ContainsFold predicate on the "operation_kind" field.
func OperationKindContainsFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContainsFold(FieldOperationKind, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldSuccess, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLTE(FieldOccurredAt, v))
}

// InteractionIDEQ applies the EQ predicate on the "interaction_id" field.
func InteractionIDEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEQ(FieldInteractionID, v))
}

// InteractionIDNEQ applies the NEQ predicate on the "interaction_id" field.
func InteractionIDNEQ(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNEQ(FieldInteractionID, v))
}

// InteractionIDIn applies the In predicate on the "interaction_id" field.
func InteractionIDIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIn(FieldInteractionID, vs...))
}

// InteractionIDNotIn applies the NotIn predicate on the "interaction_id" field.
func InteractionIDNotIn(vs ...string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotIn(FieldInteractionID, vs...))
}

// InteractionIDGT applies the GT predicate on the "interaction_id" field.
func InteractionIDGT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGT(FieldInteractionID, v))
}

// InteractionIDGTE applies the GTE predicate on the "interaction_id" field.
func InteractionIDGTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldGTE(FieldInteractionID, v))
}

// InteractionIDLT applies the LT predicate on the "interaction_id" field.
func InteractionIDLT(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLT(FieldInteractionID, v))
}

// InteractionIDLTE applies the LTE predicate on the "interaction_id" field.
func InteractionIDLTE(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldLTE(FieldInteractionID, v))
}

// InteractionIDContains applies the Contains predicate on the "interaction_id" field.
func InteractionIDContains(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContains(FieldInteractionID, v))
}

// InteractionIDHasPrefix applies the HasPrefix predicate on the "interaction_id" field.
func InteractionIDHasPrefix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasPrefix(FieldInteractionID, v))
}

// InteractionIDHasSuffix applies the HasSuffix predicate on the "interaction_id" field.
func InteractionIDHasSuffix(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldHasSuffix(FieldInteractionID, v))
}

// InteractionIDIsNil applies the IsNil predicate on the "interaction_id" field.
func InteractionIDIsNil() predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldIsNull(FieldInteractionID))
}

// InteractionIDNotNil applies the NotNil predicate on the "interaction_id" field.
func InteractionIDNotNil() predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldNotNull(FieldInteractionID))
}

// InteractionIDEqualFold applies the EqualFold predicate on the "interaction_id" field.
func InteractionIDEqualFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldEqualFold(FieldInteractionID, v))
}

// InteractionIDContainsFold applies the ContainsFold predicate on the "interaction_id" field.
func InteractionIDContainsFold(v string) predicate.OperationRecord {
	return predicate.OperationRecord(sql.FieldContainsFold(FieldInteractionID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OperationRecord) predicate.OperationRecord {
	return predicate.OperationRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OperationRecord) predicate.OperationRecord {
	return predicate.OperationRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OperationRecord) predicate.OperationRecord {
	return predicate.OperationRecord(sql.NotPredicates(p))
}
