// Code generated by ent, DO NOT EDIT.

package remindchannel

import (
	"entgo.io/ent/dialect/sql"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldMessageID, v))
}

// ListTitle applies equality check predicate on the "list_title" field. It's identical to ListTitleEQ.
func ListTitle(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldListTitle, v))
}

// OperationLogThreadID applies equality check predicate on the "operation_log_thread_id" field. It's identical to OperationLogThreadIDEQ.
func OperationLogThreadID(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldOperationLogThreadID, v))
}

// RemindNoticeThreadID applies equality check predicate on the "remind_notice_thread_id" field. It's identical to RemindNoticeThreadIDEQ.
func RemindNoticeThreadID(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldRemindNoticeThreadID, v))
}

// RemindNoticeMessageID applies equality check predicate on the "remind_notice_message_id" field. It's identical to RemindNoticeMessageIDEQ.
func RemindNoticeMessageID(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldRemindNoticeMessageID, v))
}

// LinkedInventoryChannelID applies equality check predicate on the "linked_inventory_channel_id" field. It's identical to LinkedInventoryChannelIDEQ.
func LinkedInventoryChannelID(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldLinkedInventoryChannelID, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDIsNil applies the IsNil predicate on the "message_id" field.
func MessageIDIsNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIsNull(FieldMessageID))
}

// MessageIDNotNil applies the NotNil predicate on the "message_id" field.
func MessageIDNotNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotNull(FieldMessageID))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldMessageID, v))
}

// ListTitleEQ applies the EQ predicate on the "list_title" field.
func ListTitleEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldListTitle, v))
}

// ListTitleNEQ applies the NEQ predicate on the "list_title" field.
func ListTitleNEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldListTitle, v))
}

// ListTitleIn applies the In predicate on the "list_title" field.
func ListTitleIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldListTitle, vs...))
}

// ListTitleNotIn applies the NotIn predicate on the "list_title" field.
func ListTitleNotIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldListTitle, vs...))
}

// ListTitleGT applies the GT predicate on the "list_title" field.
func ListTitleGT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldListTitle, v))
}

// ListTitleGTE applies the GTE predicate on the "list_title" field.
func ListTitleGTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldListTitle, v))
}

// ListTitleLT applies the LT predicate on the "list_title" field.
func ListTitleLT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldListTitle, v))
}

// ListTitleLTE applies the LTE predicate on the "list_title" field.
func ListTitleLTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldListTitle, v))
}

// ListTitleContains applies the Contains predicate on the "list_title" field.
func ListTitleContains(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContains(FieldListTitle, v))
}

// ListTitleHasPrefix applies the HasPrefix predicate on the "list_title" field.
func ListTitleHasPrefix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasPrefix(FieldListTitle, v))
}

// ListTitleHasSuffix applies the HasSuffix predicate on the "list_title" field.
func ListTitleHasSuffix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasSuffix(FieldListTitle, v))
}

// ListTitleEqualFold applies the EqualFold predicate on the "list_title" field.
func ListTitleEqualFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldListTitle, v))
}

// ListTitleContainsFold applies the ContainsFold predicate on the "list_title" field.
func ListTitleContainsFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldListTitle, v))
}

// OperationLogThreadIDEQ applies the EQ predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDNEQ applies the NEQ predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDNEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDIn applies the In predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldOperationLogThreadID, vs...))
}

// OperationLogThreadIDNotIn applies the NotIn predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDNotIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldOperationLogThreadID, vs...))
}

// OperationLogThreadIDGT applies the GT predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDGT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDGTE applies the GTE predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDGTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDLT applies the LT predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDLT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDLTE applies the LTE predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDLTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDContains applies the Contains predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDContains(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContains(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDHasPrefix applies the HasPrefix predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDHasPrefix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasPrefix(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDHasSuffix applies the HasSuffix predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDHasSuffix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasSuffix(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDIsNil applies the IsNil predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDIsNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIsNull(FieldOperationLogThreadID))
}

// OperationLogThreadIDNotNil applies the NotNil predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDNotNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotNull(FieldOperationLogThreadID))
}

// OperationLogThreadIDEqualFold applies the EqualFold predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDEqualFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDContainsFold applies the ContainsFold predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDContainsFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldOperationLogThreadID, v))
}

// RemindNoticeThreadIDEQ applies the EQ predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDNEQ applies the NEQ predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDNEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDIn applies the In predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldRemindNoticeThreadID, vs...))
}

// RemindNoticeThreadIDNotIn applies the NotIn predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDNotIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldRemindNoticeThreadID, vs...))
}

// RemindNoticeThreadIDGT applies the GT predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDGT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDGTE applies the GTE predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDGTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDLT applies the LT predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDLT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDLTE applies the LTE predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDLTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDContains applies the Contains predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDContains(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContains(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDHasPrefix applies the HasPrefix predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDHasPrefix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasPrefix(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDHasSuffix applies the HasSuffix predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDHasSuffix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasSuffix(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDIsNil applies the IsNil predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDIsNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIsNull(FieldRemindNoticeThreadID))
}

// RemindNoticeThreadIDNotNil applies the NotNil predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDNotNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotNull(FieldRemindNoticeThreadID))
}

// RemindNoticeThreadIDEqualFold applies the EqualFold predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDEqualFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldRemindNoticeThreadID, v))
}

// RemindNoticeThreadIDContainsFold applies the ContainsFold predicate on the "remind_notice_thread_id" field.
func RemindNoticeThreadIDContainsFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldRemindNoticeThreadID, v))
}

// RemindNoticeMessageIDEQ applies the EQ predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDNEQ applies the NEQ predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDNEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDIn applies the In predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldRemindNoticeMessageID, vs...))
}

// RemindNoticeMessageIDNotIn applies the NotIn predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDNotIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldRemindNoticeMessageID, vs...))
}

// RemindNoticeMessageIDGT applies the GT predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDGT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDGTE applies the GTE predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDGTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDLT applies the LT predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDLT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDLTE applies the LTE predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDLTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDContains applies the Contains predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDContains(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContains(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDHasPrefix applies the HasPrefix predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDHasPrefix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasPrefix(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDHasSuffix applies the HasSuffix predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDHasSuffix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasSuffix(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDIsNil applies the IsNil predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDIsNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIsNull(FieldRemindNoticeMessageID))
}

// RemindNoticeMessageIDNotNil applies the NotNil predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDNotNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotNull(FieldRemindNoticeMessageID))
}

// RemindNoticeMessageIDEqualFold applies the EqualFold predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDEqualFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldRemindNoticeMessageID, v))
}

// RemindNoticeMessageIDContainsFold applies the ContainsFold predicate on the "remind_notice_message_id" field.
func RemindNoticeMessageIDContainsFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldRemindNoticeMessageID, v))
}

// LinkedInventoryChannelIDEQ applies the EQ predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEQ(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDNEQ applies the NEQ predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDNEQ(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNEQ(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDIn applies the In predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIn(FieldLinkedInventoryChannelID, vs...))
}

// LinkedInventoryChannelIDNotIn applies the NotIn predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDNotIn(vs ...string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotIn(FieldLinkedInventoryChannelID, vs...))
}

// LinkedInventoryChannelIDGT applies the GT predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDGT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGT(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDGTE applies the GTE predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDGTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldGTE(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDLT applies the LT predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDLT(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLT(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDLTE applies the LTE predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDLTE(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldLTE(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDContains applies the Contains predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDContains(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContains(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDHasPrefix applies the HasPrefix predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDHasPrefix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasPrefix(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDHasSuffix applies the HasSuffix predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDHasSuffix(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldHasSuffix(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDIsNil applies the IsNil predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDIsNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldIsNull(FieldLinkedInventoryChannelID))
}

// LinkedInventoryChannelIDNotNil applies the NotNil predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDNotNil() predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldNotNull(FieldLinkedInventoryChannelID))
}

// LinkedInventoryChannelIDEqualFold applies the EqualFold predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDEqualFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldEqualFold(FieldLinkedInventoryChannelID, v))
}

// LinkedInventoryChannelIDContainsFold applies the ContainsFold predicate on the "linked_inventory_channel_id" field.
func LinkedInventoryChannelIDContainsFold(v string) predicate.RemindChannel {
	return predicate.RemindChannel(sql.FieldContainsFold(FieldLinkedInventoryChannelID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RemindChannel) predicate.RemindChannel {
	return predicate.RemindChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RemindChannel) predicate.RemindChannel {
	return predicate.RemindChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RemindChannel) predicate.RemindChannel {
	return predicate.RemindChannel(sql.NotPredicates(p))
}
