// Code generated by ent, DO NOT EDIT.

package inventorychannel

import (
	"entgo.io/ent/dialect/sql"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContainsFold(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldMessageID, v))
}

// ListTitle applies equality check predicate on the "list_title" field. It's identical to ListTitleEQ.
func ListTitle(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldListTitle, v))
}

// OperationLogThreadID applies equality check predicate on the "operation_log_thread_id" field. It's identical to OperationLogThreadIDEQ.
func OperationLogThreadID(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldOperationLogThreadID, v))
}

// DefaultCategory applies equality check predicate on the "default_category" field. It's identical to DefaultCategoryEQ.
func DefaultCategory(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldDefaultCategory, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDIsNil applies the IsNil predicate on the "message_id" field.
func MessageIDIsNil() predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIsNull(FieldMessageID))
}

// MessageIDNotNil applies the NotNil predicate on the "message_id" field.
func MessageIDNotNil() predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotNull(FieldMessageID))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContainsFold(FieldMessageID, v))
}

// ListTitleEQ applies the EQ predicate on the "list_title" field.
func ListTitleEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldListTitle, v))
}

// ListTitleNEQ applies the NEQ predicate on the "list_title" field.
func ListTitleNEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNEQ(FieldListTitle, v))
}

// ListTitleIn applies the In predicate on the "list_title" field.
func ListTitleIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIn(FieldListTitle, vs...))
}

// ListTitleNotIn applies the NotIn predicate on the "list_title" field.
func ListTitleNotIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotIn(FieldListTitle, vs...))
}

// ListTitleGT applies the GT predicate on the "list_title" field.
func ListTitleGT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGT(FieldListTitle, v))
}

// ListTitleGTE applies the GTE predicate on the "list_title" field.
func ListTitleGTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGTE(FieldListTitle, v))
}

// ListTitleLT applies the LT predicate on the "list_title" field.
func ListTitleLT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLT(FieldListTitle, v))
}

// ListTitleLTE applies the LTE predicate on the "list_title" field.
func ListTitleLTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLTE(FieldListTitle, v))
}

// ListTitleContains applies the Contains predicate on the "list_title" field.
func ListTitleContains(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContains(FieldListTitle, v))
}

// ListTitleHasPrefix applies the HasPrefix predicate on the "list_title" field.
func ListTitleHasPrefix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasPrefix(FieldListTitle, v))
}

// ListTitleHasSuffix applies the HasSuffix predicate on the "list_title" field.
func ListTitleHasSuffix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasSuffix(FieldListTitle, v))
}

// ListTitleEqualFold applies the EqualFold predicate on the "list_title" field.
func ListTitleEqualFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEqualFold(FieldListTitle, v))
}

// ListTitleContainsFold applies the ContainsFold predicate on the "list_title" field.
func ListTitleContainsFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContainsFold(FieldListTitle, v))
}

// OperationLogThreadIDEQ applies the EQ predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDNEQ applies the NEQ predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDNEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNEQ(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDIn applies the In predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIn(FieldOperationLogThreadID, vs...))
}

// OperationLogThreadIDNotIn applies the NotIn predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDNotIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotIn(FieldOperationLogThreadID, vs...))
}

// OperationLogThreadIDGT applies the GT predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDGT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGT(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDGTE applies the GTE predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDGTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGTE(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDLT applies the LT predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDLT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLT(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDLTE applies the LTE predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDLTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLTE(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDContains applies the Contains predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDContains(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContains(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDHasPrefix applies the HasPrefix predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDHasPrefix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasPrefix(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDHasSuffix applies the HasSuffix predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDHasSuffix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasSuffix(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDIsNil applies the IsNil predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDIsNil() predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIsNull(FieldOperationLogThreadID))
}

// OperationLogThreadIDNotNil applies the NotNil predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDNotNil() predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotNull(FieldOperationLogThreadID))
}

// OperationLogThreadIDEqualFold applies the EqualFold predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDEqualFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEqualFold(FieldOperationLogThreadID, v))
}

// OperationLogThreadIDContainsFold applies the ContainsFold predicate on the "operation_log_thread_id" field.
func OperationLogThreadIDContainsFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContainsFold(FieldOperationLogThreadID, v))
}

// DefaultCategoryEQ applies the EQ predicate on the "default_category" field.
func DefaultCategoryEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEQ(FieldDefaultCategory, v))
}

// DefaultCategoryNEQ applies the NEQ predicate on the "default_category" field.
func DefaultCategoryNEQ(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNEQ(FieldDefaultCategory, v))
}

// DefaultCategoryIn applies the In predicate on the "default_category" field.
func DefaultCategoryIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldIn(FieldDefaultCategory, vs...))
}

// DefaultCategoryNotIn applies the NotIn predicate on the "default_category" field.
func DefaultCategoryNotIn(vs ...string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldNotIn(FieldDefaultCategory, vs...))
}

// DefaultCategoryGT applies the GT predicate on the "default_category" field.
func DefaultCategoryGT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGT(FieldDefaultCategory, v))
}

// DefaultCategoryGTE applies the GTE predicate on the "default_category" field.
func DefaultCategoryGTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldGTE(FieldDefaultCategory, v))
}

// DefaultCategoryLT applies the LT predicate on the "default_category" field.
func DefaultCategoryLT(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLT(FieldDefaultCategory, v))
}

// DefaultCategoryLTE applies the LTE predicate on the "default_category" field.
func DefaultCategoryLTE(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldLTE(FieldDefaultCategory, v))
}

// DefaultCategoryContains applies the Contains predicate on the "default_category" field.
func DefaultCategoryContains(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContains(FieldDefaultCategory, v))
}

// DefaultCategoryHasPrefix applies the HasPrefix predicate on the "default_category" field.
func DefaultCategoryHasPrefix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasPrefix(FieldDefaultCategory, v))
}

// DefaultCategoryHasSuffix applies the HasSuffix predicate on the "default_category" field.
func DefaultCategoryHasSuffix(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldHasSuffix(FieldDefaultCategory, v))
}

// DefaultCategoryEqualFold applies the EqualFold predicate on the "default_category" field.
func DefaultCategoryEqualFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldEqualFold(FieldDefaultCategory, v))
}

// DefaultCategoryContainsFold applies the ContainsFold predicate on the "default_category" field.
func DefaultCategoryContainsFold(v string) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.FieldContainsFold(FieldDefaultCategory, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InventoryChannel) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InventoryChannel) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InventoryChannel) predicate.InventoryChannel {
	return predicate.InventoryChannel(sql.NotPredicates(p))
}
