package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// SQL migrations own constraints and identity columns; ent does not run DDL.
// output_order is generated by PostgreSQL and must be omitted on insertion.
// Its sequence default annotation permits omission in generated builders.

type OperationRecord struct{ ent.Schema }

func (OperationRecord) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "operation_records"}}
}
func (OperationRecord) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Immutable().Annotations(entsql.DefaultExpr("uuidv7()")), field.String("channel_id"), field.String("actor_id"),
		field.String("operation_kind"), field.Bool("success"), field.Time("occurred_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}),
		field.JSON("facts", json.RawMessage{}).SchemaType(map[string]string{dialect.Postgres: "jsonb"}), field.String("interaction_id").Optional().Nillable().Unique(),
	}
}

type OutputTask struct{ ent.Schema }

func (OutputTask) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "output_tasks"}}
}
func (OutputTask) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Immutable().Annotations(entsql.DefaultExpr("uuidv7()")), field.String("channel_id"), field.String("kind"),
		field.String("target_id"), field.UUID("operation_id", uuid.UUID{}).Optional().Nillable(),
		field.JSON("payload", json.RawMessage{}).SchemaType(map[string]string{dialect.Postgres: "jsonb"}), field.String("destination_key"),
		field.String("dedup_key").Optional().Nillable().Unique(), field.Int64("output_order").Immutable().Unique().Annotations(entsql.DefaultExpr("nextval('output_tasks_output_order_seq'::regclass)")),
		field.String("state"), field.Int("attempts").NonNegative().Default(0), field.Time("available_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}),
		field.String("executor").Default(""), field.String("last_error").Default(""),
		field.Time("created_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}), field.Time("updated_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}),
	}
}

type OutputDispatch struct{ ent.Schema }

func (OutputDispatch) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "output_dispatches"}}
}
func (OutputDispatch) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Immutable().Annotations(entsql.DefaultExpr("uuidv7()")), field.UUID("task_id", uuid.UUID{}),
		field.Int("attempt").Positive(), field.String("nonce").Default(""), field.Time("started_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}),
		field.Time("finished_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}).Optional().Nillable(), field.String("outcome"), field.String("discord_message_id").Default(""),
	}
}
func (OutputDispatch) Indexes() []ent.Index {
	return []ent.Index{index.Fields("task_id", "attempt").Unique()}
}

type ChannelOutputSuspension struct{ ent.Schema }

func (ChannelOutputSuspension) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "channel_output_suspensions"}}
}
func (ChannelOutputSuspension) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("channel_id").Immutable(), field.Time("suspended_at").SchemaType(map[string]string{dialect.Postgres: "timestamptz"}), field.String("suspended_by")}
}

type DiscordCardView struct{ ent.Schema }

func (DiscordCardView) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "discord_card_views"}}
}
func (DiscordCardView) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Immutable().Annotations(entsql.DefaultExpr("uuidv7()")), field.String("channel_id"), field.String("target_kind"),
		field.String("target_id"), field.String("mode"), field.Int("page").NonNegative(), field.Int64("view_version").Positive(),
	}
}
func (DiscordCardView) Indexes() []ent.Index {
	return []ent.Index{index.Fields("channel_id", "target_kind", "target_id").Unique()}
}
