emit:
  - "@typespec/openapi3"
output-dir: "{project-root}/generated"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}"
    openapi-versions:
      - "3.0.0"
    output-file: openapi.yaml
