// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/channeloutputsuspension"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ChannelOutputSuspensionUpdate is the builder for updating ChannelOutputSuspension entities.
type ChannelOutputSuspensionUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelOutputSuspensionMutation
}

// Where appends a list predicates to the ChannelOutputSuspensionUpdate builder.
func (_u *ChannelOutputSuspensionUpdate) Where(ps ...predicate.ChannelOutputSuspension) *ChannelOutputSuspensionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSuspendedAt sets the "suspended_at" field.
func (_u *ChannelOutputSuspensionUpdate) SetSuspendedAt(v time.Time) *ChannelOutputSuspensionUpdate {
	_u.mutation.SetSuspendedAt(v)
	return _u
}

// SetNillableSuspendedAt sets the "suspended_at" field if the given value is not nil.
func (_u *ChannelOutputSuspensionUpdate) SetNillableSuspendedAt(v *time.Time) *ChannelOutputSuspensionUpdate {
	if v != nil {
		_u.SetSuspendedAt(*v)
	}
	return _u
}

// SetSuspendedBy sets the "suspended_by" field.
func (_u *ChannelOutputSuspensionUpdate) SetSuspendedBy(v string) *ChannelOutputSuspensionUpdate {
	_u.mutation.SetSuspendedBy(v)
	return _u
}

// SetNillableSuspendedBy sets the "suspended_by" field if the given value is not nil.
func (_u *ChannelOutputSuspensionUpdate) SetNillableSuspendedBy(v *string) *ChannelOutputSuspensionUpdate {
	if v != nil {
		_u.SetSuspendedBy(*v)
	}
	return _u
}

// Mutation returns the ChannelOutputSuspensionMutation object of the builder.
func (_u *ChannelOutputSuspensionUpdate) Mutation() *ChannelOutputSuspensionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelOutputSuspensionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelOutputSuspensionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelOutputSuspensionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelOutputSuspensionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChannelOutputSuspensionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(channeloutputsuspension.Table, channeloutputsuspension.Columns, sqlgraph.NewFieldSpec(channeloutputsuspension.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SuspendedAt(); ok {
		_spec.SetField(channeloutputsuspension.FieldSuspendedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SuspendedBy(); ok {
		_spec.SetField(channeloutputsuspension.FieldSuspendedBy, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channeloutputsuspension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelOutputSuspensionUpdateOne is the builder for updating a single ChannelOutputSuspension entity.
type ChannelOutputSuspensionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelOutputSuspensionMutation
}

// SetSuspendedAt sets the "suspended_at" field.
func (_u *ChannelOutputSuspensionUpdateOne) SetSuspendedAt(v time.Time) *ChannelOutputSuspensionUpdateOne {
	_u.mutation.SetSuspendedAt(v)
	return _u
}

// SetNillableSuspendedAt sets the "suspended_at" field if the given value is not nil.
func (_u *ChannelOutputSuspensionUpdateOne) SetNillableSuspendedAt(v *time.Time) *ChannelOutputSuspensionUpdateOne {
	if v != nil {
		_u.SetSuspendedAt(*v)
	}
	return _u
}

// SetSuspendedBy sets the "suspended_by" field.
func (_u *ChannelOutputSuspensionUpdateOne) SetSuspendedBy(v string) *ChannelOutputSuspensionUpdateOne {
	_u.mutation.SetSuspendedBy(v)
	return _u
}

// SetNillableSuspendedBy sets the "suspended_by" field if the given value is not nil.
func (_u *ChannelOutputSuspensionUpdateOne) SetNillableSuspendedBy(v *string) *ChannelOutputSuspensionUpdateOne {
	if v != nil {
		_u.SetSuspendedBy(*v)
	}
	return _u
}

// Mutation returns the ChannelOutputSuspensionMutation object of the builder.
func (_u *ChannelOutputSuspensionUpdateOne) Mutation() *ChannelOutputSuspensionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelOutputSuspensionUpdate builder.
func (_u *ChannelOutputSuspensionUpdateOne) Where(ps ...predicate.ChannelOutputSuspension) *ChannelOutputSuspensionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelOutputSuspensionUpdateOne) Select(field string, fields ...string) *ChannelOutputSuspensionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelOutputSuspension entity.
func (_u *ChannelOutputSuspensionUpdateOne) Save(ctx context.Context) (*ChannelOutputSuspension, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelOutputSuspensionUpdateOne) SaveX(ctx context.Context) *ChannelOutputSuspension {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelOutputSuspensionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelOutputSuspensionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChannelOutputSuspensionUpdateOne) sqlSave(ctx context.Context) (_node *ChannelOutputSuspension, err error) {
	_spec := sqlgraph.NewUpdateSpec(channeloutputsuspension.Table, channeloutputsuspension.Columns, sqlgraph.NewFieldSpec(channeloutputsuspension.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelOutputSuspension.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channeloutputsuspension.FieldID)
		for _, f := range fields {
			if !channeloutputsuspension.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channeloutputsuspension.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SuspendedAt(); ok {
		_spec.SetField(channeloutputsuspension.FieldSuspendedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SuspendedBy(); ok {
		_spec.SetField(channeloutputsuspension.FieldSuspendedBy, field.TypeString, value)
	}
	_node = &ChannelOutputSuspension{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channeloutputsuspension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
