// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/channeloutputsuspension"
)

// ChannelOutputSuspension is the model entity for the ChannelOutputSuspension schema.
type ChannelOutputSuspension struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SuspendedAt holds the value of the "suspended_at" field.
	SuspendedAt time.Time `json:"suspended_at,omitempty"`
	// SuspendedBy holds the value of the "suspended_by" field.
	SuspendedBy  string `json:"suspended_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelOutputSuspension) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channeloutputsuspension.FieldID, channeloutputsuspension.FieldSuspendedBy:
			values[i] = new(sql.NullString)
		case channeloutputsuspension.FieldSuspendedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelOutputSuspension fields.
func (_m *ChannelOutputSuspension) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channeloutputsuspension.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case channeloutputsuspension.FieldSuspendedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field suspended_at", values[i])
			} else if value.Valid {
				_m.SuspendedAt = value.Time
			}
		case channeloutputsuspension.FieldSuspendedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field suspended_by", values[i])
			} else if value.Valid {
				_m.SuspendedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelOutputSuspension.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelOutputSuspension) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChannelOutputSuspension.
// Note that you need to call ChannelOutputSuspension.Unwrap() before calling this method if this ChannelOutputSuspension
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelOutputSuspension) Update() *ChannelOutputSuspensionUpdateOne {
	return NewChannelOutputSuspensionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelOutputSuspension entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelOutputSuspension) Unwrap() *ChannelOutputSuspension {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelOutputSuspension is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelOutputSuspension) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelOutputSuspension(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("suspended_at=")
	builder.WriteString(_m.SuspendedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("suspended_by=")
	builder.WriteString(_m.SuspendedBy)
	builder.WriteByte(')')
	return builder.String()
}

// ChannelOutputSuspensions is a parsable slice of ChannelOutputSuspension.
type ChannelOutputSuspensions []*ChannelOutputSuspension
