// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/channeloutputsuspension"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/discordcardview"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/inventorychannel"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/inventoryitem"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/listchannel"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/listitem"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/operationrecord"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/outputdispatch"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/outputtask"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/remindchannel"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/remindtask"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/remindtaskinventoryitem"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ChannelOutputSuspension is the client for interacting with the ChannelOutputSuspension builders.
	ChannelOutputSuspension *ChannelOutputSuspensionClient
	// DiscordCardView is the client for interacting with the DiscordCardView builders.
	DiscordCardView *DiscordCardViewClient
	// InventoryChannel is the client for interacting with the InventoryChannel builders.
	InventoryChannel *InventoryChannelClient
	// InventoryItem is the client for interacting with the InventoryItem builders.
	InventoryItem *InventoryItemClient
	// ListChannel is the client for interacting with the ListChannel builders.
	ListChannel *ListChannelClient
	// ListItem is the client for interacting with the ListItem builders.
	ListItem *ListItemClient
	// OperationRecord is the client for interacting with the OperationRecord builders.
	OperationRecord *OperationRecordClient
	// OutputDispatch is the client for interacting with the OutputDispatch builders.
	OutputDispatch *OutputDispatchClient
	// OutputTask is the client for interacting with the OutputTask builders.
	OutputTask *OutputTaskClient
	// RemindChannel is the client for interacting with the RemindChannel builders.
	RemindChannel *RemindChannelClient
	// RemindTask is the client for interacting with the RemindTask builders.
	RemindTask *RemindTaskClient
	// RemindTaskInventoryItem is the client for interacting with the RemindTaskInventoryItem builders.
	RemindTaskInventoryItem *RemindTaskInventoryItemClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ChannelOutputSuspension = NewChannelOutputSuspensionClient(c.config)
	c.DiscordCardView = NewDiscordCardViewClient(c.config)
	c.InventoryChannel = NewInventoryChannelClient(c.config)
	c.InventoryItem = NewInventoryItemClient(c.config)
	c.ListChannel = NewListChannelClient(c.config)
	c.ListItem = NewListItemClient(c.config)
	c.OperationRecord = NewOperationRecordClient(c.config)
	c.OutputDispatch = NewOutputDispatchClient(c.config)
	c.OutputTask = NewOutputTaskClient(c.config)
	c.RemindChannel = NewRemindChannelClient(c.config)
	c.RemindTask = NewRemindTaskClient(c.config)
	c.RemindTaskInventoryItem = NewRemindTaskInventoryItemClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                     ctx,
		config:                  cfg,
		ChannelOutputSuspension: NewChannelOutputSuspensionClient(cfg),
		DiscordCardView:         NewDiscordCardViewClient(cfg),
		InventoryChannel:        NewInventoryChannelClient(cfg),
		InventoryItem:           NewInventoryItemClient(cfg),
		ListChannel:             NewListChannelClient(cfg),
		ListItem:                NewListItemClient(cfg),
		OperationRecord:         NewOperationRecordClient(cfg),
		OutputDispatch:          NewOutputDispatchClient(cfg),
		OutputTask:              NewOutputTaskClient(cfg),
		RemindChannel:           NewRemindChannelClient(cfg),
		RemindTask:              NewRemindTaskClient(cfg),
		RemindTaskInventoryItem: NewRemindTaskInventoryItemClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                     ctx,
		config:                  cfg,
		ChannelOutputSuspension: NewChannelOutputSuspensionClient(cfg),
		DiscordCardView:         NewDiscordCardViewClient(cfg),
		InventoryChannel:        NewInventoryChannelClient(cfg),
		InventoryItem:           NewInventoryItemClient(cfg),
		ListChannel:             NewListChannelClient(cfg),
		ListItem:                NewListItemClient(cfg),
		OperationRecord:         NewOperationRecordClient(cfg),
		OutputDispatch:          NewOutputDispatchClient(cfg),
		OutputTask:              NewOutputTaskClient(cfg),
		RemindChannel:           NewRemindChannelClient(cfg),
		RemindTask:              NewRemindTaskClient(cfg),
		RemindTaskInventoryItem: NewRemindTaskInventoryItemClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ChannelOutputSuspension.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ChannelOutputSuspension, c.DiscordCardView, c.InventoryChannel,
		c.InventoryItem, c.ListChannel, c.ListItem, c.OperationRecord,
		c.OutputDispatch, c.OutputTask, c.RemindChannel, c.RemindTask,
		c.RemindTaskInventoryItem,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ChannelOutputSuspension, c.DiscordCardView, c.InventoryChannel,
		c.InventoryItem, c.ListChannel, c.ListItem, c.OperationRecord,
		c.OutputDispatch, c.OutputTask, c.RemindChannel, c.RemindTask,
		c.RemindTaskInventoryItem,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChannelOutputSuspensionMutation:
		return c.ChannelOutputSuspension.mutate(ctx, m)
	case *DiscordCardViewMutation:
		return c.DiscordCardView.mutate(ctx, m)
	case *InventoryChannelMutation:
		return c.InventoryChannel.mutate(ctx, m)
	case *InventoryItemMutation:
		return c.InventoryItem.mutate(ctx, m)
	case *ListChannelMutation:
		return c.ListChannel.mutate(ctx, m)
	case *ListItemMutation:
		return c.ListItem.mutate(ctx, m)
	case *OperationRecordMutation:
		return c.OperationRecord.mutate(ctx, m)
	case *OutputDispatchMutation:
		return c.OutputDispatch.mutate(ctx, m)
	case *OutputTaskMutation:
		return c.OutputTask.mutate(ctx, m)
	case *RemindChannelMutation:
		return c.RemindChannel.mutate(ctx, m)
	case *RemindTaskMutation:
		return c.RemindTask.mutate(ctx, m)
	case *RemindTaskInventoryItemMutation:
		return c.RemindTaskInventoryItem.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChannelOutputSuspensionClient is a client for the ChannelOutputSuspension schema.
type ChannelOutputSuspensionClient struct {
	config
}

// NewChannelOutputSuspensionClient returns a client for the ChannelOutputSuspension from the given config.
func NewChannelOutputSuspensionClient(c config) *ChannelOutputSuspensionClient {
	return &ChannelOutputSuspensionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channeloutputsuspension.Hooks(f(g(h())))`.
func (c *ChannelOutputSuspensionClient) Use(hooks ...Hook) {
	c.hooks.ChannelOutputSuspension = append(c.hooks.ChannelOutputSuspension, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channeloutputsuspension.Intercept(f(g(h())))`.
func (c *ChannelOutputSuspensionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChannelOutputSuspension = append(c.inters.ChannelOutputSuspension, interceptors...)
}

// Create returns a builder for creating a ChannelOutputSuspension entity.
func (c *ChannelOutputSuspensionClient) Create() *ChannelOutputSuspensionCreate {
	mutation := newChannelOutputSuspensionMutation(c.config, OpCreate)
	return &ChannelOutputSuspensionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChannelOutputSuspension entities.
func (c *ChannelOutputSuspensionClient) CreateBulk(builders ...*ChannelOutputSuspensionCreate) *ChannelOutputSuspensionCreateBulk {
	return &ChannelOutputSuspensionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelOutputSuspensionClient) MapCreateBulk(slice any, setFunc func(*ChannelOutputSuspensionCreate, int)) *ChannelOutputSuspensionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelOutputSuspensionCreateBulk{err: fmt.Errorf("calling to ChannelOutputSuspensionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelOutputSuspensionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelOutputSuspensionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChannelOutputSuspension.
func (c *ChannelOutputSuspensionClient) Update() *ChannelOutputSuspensionUpdate {
	mutation := newChannelOutputSuspensionMutation(c.config, OpUpdate)
	return &ChannelOutputSuspensionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelOutputSuspensionClient) UpdateOne(_m *ChannelOutputSuspension) *ChannelOutputSuspensionUpdateOne {
	mutation := newChannelOutputSuspensionMutation(c.config, OpUpdateOne, withChannelOutputSuspension(_m))
	return &ChannelOutputSuspensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelOutputSuspensionClient) UpdateOneID(id string) *ChannelOutputSuspensionUpdateOne {
	mutation := newChannelOutputSuspensionMutation(c.config, OpUpdateOne, withChannelOutputSuspensionID(id))
	return &ChannelOutputSuspensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChannelOutputSuspension.
func (c *ChannelOutputSuspensionClient) Delete() *ChannelOutputSuspensionDelete {
	mutation := newChannelOutputSuspensionMutation(c.config, OpDelete)
	return &ChannelOutputSuspensionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelOutputSuspensionClient) DeleteOne(_m *ChannelOutputSuspension) *ChannelOutputSuspensionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelOutputSuspensionClient) DeleteOneID(id string) *ChannelOutputSuspensionDeleteOne {
	builder := c.Delete().Where(channeloutputsuspension.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelOutputSuspensionDeleteOne{builder}
}

// Query returns a query builder for ChannelOutputSuspension.
func (c *ChannelOutputSuspensionClient) Query() *ChannelOutputSuspensionQuery {
	return &ChannelOutputSuspensionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannelOutputSuspension},
		inters: c.Interceptors(),
	}
}

// Get returns a ChannelOutputSuspension entity by its id.
func (c *ChannelOutputSuspensionClient) Get(ctx context.Context, id string) (*ChannelOutputSuspension, error) {
	return c.Query().Where(channeloutputsuspension.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelOutputSuspensionClient) GetX(ctx context.Context, id string) *ChannelOutputSuspension {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChannelOutputSuspensionClient) Hooks() []Hook {
	return c.hooks.ChannelOutputSuspension
}

// Interceptors returns the client interceptors.
func (c *ChannelOutputSuspensionClient) Interceptors() []Interceptor {
	return c.inters.ChannelOutputSuspension
}

func (c *ChannelOutputSuspensionClient) mutate(ctx context.Context, m *ChannelOutputSuspensionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelOutputSuspensionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelOutputSuspensionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelOutputSuspensionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelOutputSuspensionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChannelOutputSuspension mutation op: %q", m.Op())
	}
}

// DiscordCardViewClient is a client for the DiscordCardView schema.
type DiscordCardViewClient struct {
	config
}

// NewDiscordCardViewClient returns a client for the DiscordCardView from the given config.
func NewDiscordCardViewClient(c config) *DiscordCardViewClient {
	return &DiscordCardViewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `discordcardview.Hooks(f(g(h())))`.
func (c *DiscordCardViewClient) Use(hooks ...Hook) {
	c.hooks.DiscordCardView = append(c.hooks.DiscordCardView, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `discordcardview.Intercept(f(g(h())))`.
func (c *DiscordCardViewClient) Intercept(interceptors ...Interceptor) {
	c.inters.DiscordCardView = append(c.inters.DiscordCardView, interceptors...)
}

// Create returns a builder for creating a DiscordCardView entity.
func (c *DiscordCardViewClient) Create() *DiscordCardViewCreate {
	mutation := newDiscordCardViewMutation(c.config, OpCreate)
	return &DiscordCardViewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DiscordCardView entities.
func (c *DiscordCardViewClient) CreateBulk(builders ...*DiscordCardViewCreate) *DiscordCardViewCreateBulk {
	return &DiscordCardViewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DiscordCardViewClient) MapCreateBulk(slice any, setFunc func(*DiscordCardViewCreate, int)) *DiscordCardViewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DiscordCardViewCreateBulk{err: fmt.Errorf("calling to DiscordCardViewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DiscordCardViewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DiscordCardViewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DiscordCardView.
func (c *DiscordCardViewClient) Update() *DiscordCardViewUpdate {
	mutation := newDiscordCardViewMutation(c.config, OpUpdate)
	return &DiscordCardViewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DiscordCardViewClient) UpdateOne(_m *DiscordCardView) *DiscordCardViewUpdateOne {
	mutation := newDiscordCardViewMutation(c.config, OpUpdateOne, withDiscordCardView(_m))
	return &DiscordCardViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DiscordCardViewClient) UpdateOneID(id uuid.UUID) *DiscordCardViewUpdateOne {
	mutation := newDiscordCardViewMutation(c.config, OpUpdateOne, withDiscordCardViewID(id))
	return &DiscordCardViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DiscordCardView.
func (c *DiscordCardViewClient) Delete() *DiscordCardViewDelete {
	mutation := newDiscordCardViewMutation(c.config, OpDelete)
	return &DiscordCardViewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DiscordCardViewClient) DeleteOne(_m *DiscordCardView) *DiscordCardViewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DiscordCardViewClient) DeleteOneID(id uuid.UUID) *DiscordCardViewDeleteOne {
	builder := c.Delete().Where(discordcardview.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DiscordCardViewDeleteOne{builder}
}

// Query returns a query builder for DiscordCardView.
func (c *DiscordCardViewClient) Query() *DiscordCardViewQuery {
	return &DiscordCardViewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDiscordCardView},
		inters: c.Interceptors(),
	}
}

// Get returns a DiscordCardView entity by its id.
func (c *DiscordCardViewClient) Get(ctx context.Context, id uuid.UUID) (*DiscordCardView, error) {
	return c.Query().Where(discordcardview.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DiscordCardViewClient) GetX(ctx context.Context, id uuid.UUID) *DiscordCardView {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DiscordCardViewClient) Hooks() []Hook {
	return c.hooks.DiscordCardView
}

// Interceptors returns the client interceptors.
func (c *DiscordCardViewClient) Interceptors() []Interceptor {
	return c.inters.DiscordCardView
}

func (c *DiscordCardViewClient) mutate(ctx context.Context, m *DiscordCardViewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DiscordCardViewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DiscordCardViewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DiscordCardViewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DiscordCardViewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DiscordCardView mutation op: %q", m.Op())
	}
}

// InventoryChannelClient is a client for the InventoryChannel schema.
type InventoryChannelClient struct {
	config
}

// NewInventoryChannelClient returns a client for the InventoryChannel from the given config.
func NewInventoryChannelClient(c config) *InventoryChannelClient {
	return &InventoryChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `inventorychannel.Hooks(f(g(h())))`.
func (c *InventoryChannelClient) Use(hooks ...Hook) {
	c.hooks.InventoryChannel = append(c.hooks.InventoryChannel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `inventorychannel.Intercept(f(g(h())))`.
func (c *InventoryChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.InventoryChannel = append(c.inters.InventoryChannel, interceptors...)
}

// Create returns a builder for creating a InventoryChannel entity.
func (c *InventoryChannelClient) Create() *InventoryChannelCreate {
	mutation := newInventoryChannelMutation(c.config, OpCreate)
	return &InventoryChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InventoryChannel entities.
func (c *InventoryChannelClient) CreateBulk(builders ...*InventoryChannelCreate) *InventoryChannelCreateBulk {
	return &InventoryChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InventoryChannelClient) MapCreateBulk(slice any, setFunc func(*InventoryChannelCreate, int)) *InventoryChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InventoryChannelCreateBulk{err: fmt.Errorf("calling to InventoryChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InventoryChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InventoryChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InventoryChannel.
func (c *InventoryChannelClient) Update() *InventoryChannelUpdate {
	mutation := newInventoryChannelMutation(c.config, OpUpdate)
	return &InventoryChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InventoryChannelClient) UpdateOne(_m *InventoryChannel) *InventoryChannelUpdateOne {
	mutation := newInventoryChannelMutation(c.config, OpUpdateOne, withInventoryChannel(_m))
	return &InventoryChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InventoryChannelClient) UpdateOneID(id string) *InventoryChannelUpdateOne {
	mutation := newInventoryChannelMutation(c.config, OpUpdateOne, withInventoryChannelID(id))
	return &InventoryChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InventoryChannel.
func (c *InventoryChannelClient) Delete() *InventoryChannelDelete {
	mutation := newInventoryChannelMutation(c.config, OpDelete)
	return &InventoryChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InventoryChannelClient) DeleteOne(_m *InventoryChannel) *InventoryChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InventoryChannelClient) DeleteOneID(id string) *InventoryChannelDeleteOne {
	builder := c.Delete().Where(inventorychannel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InventoryChannelDeleteOne{builder}
}

// Query returns a query builder for InventoryChannel.
func (c *InventoryChannelClient) Query() *InventoryChannelQuery {
	return &InventoryChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInventoryChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a InventoryChannel entity by its id.
func (c *InventoryChannelClient) Get(ctx context.Context, id string) (*InventoryChannel, error) {
	return c.Query().Where(inventorychannel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InventoryChannelClient) GetX(ctx context.Context, id string) *InventoryChannel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InventoryChannelClient) Hooks() []Hook {
	return c.hooks.InventoryChannel
}

// Interceptors returns the client interceptors.
func (c *InventoryChannelClient) Interceptors() []Interceptor {
	return c.inters.InventoryChannel
}

func (c *InventoryChannelClient) mutate(ctx context.Context, m *InventoryChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InventoryChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InventoryChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InventoryChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InventoryChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InventoryChannel mutation op: %q", m.Op())
	}
}

// InventoryItemClient is a client for the InventoryItem schema.
type InventoryItemClient struct {
	config
}

// NewInventoryItemClient returns a client for the InventoryItem from the given config.
func NewInventoryItemClient(c config) *InventoryItemClient {
	return &InventoryItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `inventoryitem.Hooks(f(g(h())))`.
func (c *InventoryItemClient) Use(hooks ...Hook) {
	c.hooks.InventoryItem = append(c.hooks.InventoryItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `inventoryitem.Intercept(f(g(h())))`.
func (c *InventoryItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.InventoryItem = append(c.inters.InventoryItem, interceptors...)
}

// Create returns a builder for creating a InventoryItem entity.
func (c *InventoryItemClient) Create() *InventoryItemCreate {
	mutation := newInventoryItemMutation(c.config, OpCreate)
	return &InventoryItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InventoryItem entities.
func (c *InventoryItemClient) CreateBulk(builders ...*InventoryItemCreate) *InventoryItemCreateBulk {
	return &InventoryItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InventoryItemClient) MapCreateBulk(slice any, setFunc func(*InventoryItemCreate, int)) *InventoryItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InventoryItemCreateBulk{err: fmt.Errorf("calling to InventoryItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InventoryItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InventoryItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InventoryItem.
func (c *InventoryItemClient) Update() *InventoryItemUpdate {
	mutation := newInventoryItemMutation(c.config, OpUpdate)
	return &InventoryItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InventoryItemClient) UpdateOne(_m *InventoryItem) *InventoryItemUpdateOne {
	mutation := newInventoryItemMutation(c.config, OpUpdateOne, withInventoryItem(_m))
	return &InventoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InventoryItemClient) UpdateOneID(id uuid.UUID) *InventoryItemUpdateOne {
	mutation := newInventoryItemMutation(c.config, OpUpdateOne, withInventoryItemID(id))
	return &InventoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InventoryItem.
func (c *InventoryItemClient) Delete() *InventoryItemDelete {
	mutation := newInventoryItemMutation(c.config, OpDelete)
	return &InventoryItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InventoryItemClient) DeleteOne(_m *InventoryItem) *InventoryItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InventoryItemClient) DeleteOneID(id uuid.UUID) *InventoryItemDeleteOne {
	builder := c.Delete().Where(inventoryitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InventoryItemDeleteOne{builder}
}

// Query returns a query builder for InventoryItem.
func (c *InventoryItemClient) Query() *InventoryItemQuery {
	return &InventoryItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInventoryItem},
		inters: c.Interceptors(),
	}
}

// Get returns a InventoryItem entity by its id.
func (c *InventoryItemClient) Get(ctx context.Context, id uuid.UUID) (*InventoryItem, error) {
	return c.Query().Where(inventoryitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InventoryItemClient) GetX(ctx context.Context, id uuid.UUID) *InventoryItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InventoryItemClient) Hooks() []Hook {
	return c.hooks.InventoryItem
}

// Interceptors returns the client interceptors.
func (c *InventoryItemClient) Interceptors() []Interceptor {
	return c.inters.InventoryItem
}

func (c *InventoryItemClient) mutate(ctx context.Context, m *InventoryItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InventoryItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InventoryItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InventoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InventoryItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InventoryItem mutation op: %q", m.Op())
	}
}

// ListChannelClient is a client for the ListChannel schema.
type ListChannelClient struct {
	config
}

// NewListChannelClient returns a client for the ListChannel from the given config.
func NewListChannelClient(c config) *ListChannelClient {
	return &ListChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `listchannel.Hooks(f(g(h())))`.
func (c *ListChannelClient) Use(hooks ...Hook) {
	c.hooks.ListChannel = append(c.hooks.ListChannel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `listchannel.Intercept(f(g(h())))`.
func (c *ListChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.ListChannel = append(c.inters.ListChannel, interceptors...)
}

// Create returns a builder for creating a ListChannel entity.
func (c *ListChannelClient) Create() *ListChannelCreate {
	mutation := newListChannelMutation(c.config, OpCreate)
	return &ListChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ListChannel entities.
func (c *ListChannelClient) CreateBulk(builders ...*ListChannelCreate) *ListChannelCreateBulk {
	return &ListChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ListChannelClient) MapCreateBulk(slice any, setFunc func(*ListChannelCreate, int)) *ListChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ListChannelCreateBulk{err: fmt.Errorf("calling to ListChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ListChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ListChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ListChannel.
func (c *ListChannelClient) Update() *ListChannelUpdate {
	mutation := newListChannelMutation(c.config, OpUpdate)
	return &ListChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ListChannelClient) UpdateOne(_m *ListChannel) *ListChannelUpdateOne {
	mutation := newListChannelMutation(c.config, OpUpdateOne, withListChannel(_m))
	return &ListChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ListChannelClient) UpdateOneID(id string) *ListChannelUpdateOne {
	mutation := newListChannelMutation(c.config, OpUpdateOne, withListChannelID(id))
	return &ListChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ListChannel.
func (c *ListChannelClient) Delete() *ListChannelDelete {
	mutation := newListChannelMutation(c.config, OpDelete)
	return &ListChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ListChannelClient) DeleteOne(_m *ListChannel) *ListChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ListChannelClient) DeleteOneID(id string) *ListChannelDeleteOne {
	builder := c.Delete().Where(listchannel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ListChannelDeleteOne{builder}
}

// Query returns a query builder for ListChannel.
func (c *ListChannelClient) Query() *ListChannelQuery {
	return &ListChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeListChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a ListChannel entity by its id.
func (c *ListChannelClient) Get(ctx context.Context, id string) (*ListChannel, error) {
	return c.Query().Where(listchannel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ListChannelClient) GetX(ctx context.Context, id string) *ListChannel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ListChannelClient) Hooks() []Hook {
	return c.hooks.ListChannel
}

// Interceptors returns the client interceptors.
func (c *ListChannelClient) Interceptors() []Interceptor {
	return c.inters.ListChannel
}

func (c *ListChannelClient) mutate(ctx context.Context, m *ListChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ListChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ListChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ListChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ListChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ListChannel mutation op: %q", m.Op())
	}
}

// ListItemClient is a client for the ListItem schema.
type ListItemClient struct {
	config
}

// NewListItemClient returns a client for the ListItem from the given config.
func NewListItemClient(c config) *ListItemClient {
	return &ListItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `listitem.Hooks(f(g(h())))`.
func (c *ListItemClient) Use(hooks ...Hook) {
	c.hooks.ListItem = append(c.hooks.ListItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `listitem.Intercept(f(g(h())))`.
func (c *ListItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.ListItem = append(c.inters.ListItem, interceptors...)
}

// Create returns a builder for creating a ListItem entity.
func (c *ListItemClient) Create() *ListItemCreate {
	mutation := newListItemMutation(c.config, OpCreate)
	return &ListItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ListItem entities.
func (c *ListItemClient) CreateBulk(builders ...*ListItemCreate) *ListItemCreateBulk {
	return &ListItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ListItemClient) MapCreateBulk(slice any, setFunc func(*ListItemCreate, int)) *ListItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ListItemCreateBulk{err: fmt.Errorf("calling to ListItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ListItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ListItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ListItem.
func (c *ListItemClient) Update() *ListItemUpdate {
	mutation := newListItemMutation(c.config, OpUpdate)
	return &ListItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ListItemClient) UpdateOne(_m *ListItem) *ListItemUpdateOne {
	mutation := newListItemMutation(c.config, OpUpdateOne, withListItem(_m))
	return &ListItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ListItemClient) UpdateOneID(id uuid.UUID) *ListItemUpdateOne {
	mutation := newListItemMutation(c.config, OpUpdateOne, withListItemID(id))
	return &ListItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ListItem.
func (c *ListItemClient) Delete() *ListItemDelete {
	mutation := newListItemMutation(c.config, OpDelete)
	return &ListItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ListItemClient) DeleteOne(_m *ListItem) *ListItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ListItemClient) DeleteOneID(id uuid.UUID) *ListItemDeleteOne {
	builder := c.Delete().Where(listitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ListItemDeleteOne{builder}
}

// Query returns a query builder for ListItem.
func (c *ListItemClient) Query() *ListItemQuery {
	return &ListItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeListItem},
		inters: c.Interceptors(),
	}
}

// Get returns a ListItem entity by its id.
func (c *ListItemClient) Get(ctx context.Context, id uuid.UUID) (*ListItem, error) {
	return c.Query().Where(listitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ListItemClient) GetX(ctx context.Context, id uuid.UUID) *ListItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ListItemClient) Hooks() []Hook {
	return c.hooks.ListItem
}

// Interceptors returns the client interceptors.
func (c *ListItemClient) Interceptors() []Interceptor {
	return c.inters.ListItem
}

func (c *ListItemClient) mutate(ctx context.Context, m *ListItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ListItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ListItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ListItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ListItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ListItem mutation op: %q", m.Op())
	}
}

// OperationRecordClient is a client for the OperationRecord schema.
type OperationRecordClient struct {
	config
}

// NewOperationRecordClient returns a client for the OperationRecord from the given config.
func NewOperationRecordClient(c config) *OperationRecordClient {
	return &OperationRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `operationrecord.Hooks(f(g(h())))`.
func (c *OperationRecordClient) Use(hooks ...Hook) {
	c.hooks.OperationRecord = append(c.hooks.OperationRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `operationrecord.Intercept(f(g(h())))`.
func (c *OperationRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.OperationRecord = append(c.inters.OperationRecord, interceptors...)
}

// Create returns a builder for creating a OperationRecord entity.
func (c *OperationRecordClient) Create() *OperationRecordCreate {
	mutation := newOperationRecordMutation(c.config, OpCreate)
	return &OperationRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OperationRecord entities.
func (c *OperationRecordClient) CreateBulk(builders ...*OperationRecordCreate) *OperationRecordCreateBulk {
	return &OperationRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OperationRecordClient) MapCreateBulk(slice any, setFunc func(*OperationRecordCreate, int)) *OperationRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OperationRecordCreateBulk{err: fmt.Errorf("calling to OperationRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OperationRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OperationRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OperationRecord.
func (c *OperationRecordClient) Update() *OperationRecordUpdate {
	mutation := newOperationRecordMutation(c.config, OpUpdate)
	return &OperationRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OperationRecordClient) UpdateOne(_m *OperationRecord) *OperationRecordUpdateOne {
	mutation := newOperationRecordMutation(c.config, OpUpdateOne, withOperationRecord(_m))
	return &OperationRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OperationRecordClient) UpdateOneID(id uuid.UUID) *OperationRecordUpdateOne {
	mutation := newOperationRecordMutation(c.config, OpUpdateOne, withOperationRecordID(id))
	return &OperationRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OperationRecord.
func (c *OperationRecordClient) Delete() *OperationRecordDelete {
	mutation := newOperationRecordMutation(c.config, OpDelete)
	return &OperationRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OperationRecordClient) DeleteOne(_m *OperationRecord) *OperationRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OperationRecordClient) DeleteOneID(id uuid.UUID) *OperationRecordDeleteOne {
	builder := c.Delete().Where(operationrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OperationRecordDeleteOne{builder}
}

// Query returns a query builder for OperationRecord.
func (c *OperationRecordClient) Query() *OperationRecordQuery {
	return &OperationRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOperationRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a OperationRecord entity by its id.
func (c *OperationRecordClient) Get(ctx context.Context, id uuid.UUID) (*OperationRecord, error) {
	return c.Query().Where(operationrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OperationRecordClient) GetX(ctx context.Context, id uuid.UUID) *OperationRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OperationRecordClient) Hooks() []Hook {
	return c.hooks.OperationRecord
}

// Interceptors returns the client interceptors.
func (c *OperationRecordClient) Interceptors() []Interceptor {
	return c.inters.OperationRecord
}

func (c *OperationRecordClient) mutate(ctx context.Context, m *OperationRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OperationRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OperationRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OperationRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OperationRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OperationRecord mutation op: %q", m.Op())
	}
}

// OutputDispatchClient is a client for the OutputDispatch schema.
type OutputDispatchClient struct {
	config
}

// NewOutputDispatchClient returns a client for the OutputDispatch from the given config.
func NewOutputDispatchClient(c config) *OutputDispatchClient {
	return &OutputDispatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `outputdispatch.Hooks(f(g(h())))`.
func (c *OutputDispatchClient) Use(hooks ...Hook) {
	c.hooks.OutputDispatch = append(c.hooks.OutputDispatch, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `outputdispatch.Intercept(f(g(h())))`.
func (c *OutputDispatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.OutputDispatch = append(c.inters.OutputDispatch, interceptors...)
}

// Create returns a builder for creating a OutputDispatch entity.
func (c *OutputDispatchClient) Create() *OutputDispatchCreate {
	mutation := newOutputDispatchMutation(c.config, OpCreate)
	return &OutputDispatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OutputDispatch entities.
func (c *OutputDispatchClient) CreateBulk(builders ...*OutputDispatchCreate) *OutputDispatchCreateBulk {
	return &OutputDispatchCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OutputDispatchClient) MapCreateBulk(slice any, setFunc func(*OutputDispatchCreate, int)) *OutputDispatchCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OutputDispatchCreateBulk{err: fmt.Errorf("calling to OutputDispatchClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OutputDispatchCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OutputDispatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OutputDispatch.
func (c *OutputDispatchClient) Update() *OutputDispatchUpdate {
	mutation := newOutputDispatchMutation(c.config, OpUpdate)
	return &OutputDispatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OutputDispatchClient) UpdateOne(_m *OutputDispatch) *OutputDispatchUpdateOne {
	mutation := newOutputDispatchMutation(c.config, OpUpdateOne, withOutputDispatch(_m))
	return &OutputDispatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OutputDispatchClient) UpdateOneID(id uuid.UUID) *OutputDispatchUpdateOne {
	mutation := newOutputDispatchMutation(c.config, OpUpdateOne, withOutputDispatchID(id))
	return &OutputDispatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OutputDispatch.
func (c *OutputDispatchClient) Delete() *OutputDispatchDelete {
	mutation := newOutputDispatchMutation(c.config, OpDelete)
	return &OutputDispatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OutputDispatchClient) DeleteOne(_m *OutputDispatch) *OutputDispatchDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OutputDispatchClient) DeleteOneID(id uuid.UUID) *OutputDispatchDeleteOne {
	builder := c.Delete().Where(outputdispatch.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OutputDispatchDeleteOne{builder}
}

// Query returns a query builder for OutputDispatch.
func (c *OutputDispatchClient) Query() *OutputDispatchQuery {
	return &OutputDispatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOutputDispatch},
		inters: c.Interceptors(),
	}
}

// Get returns a OutputDispatch entity by its id.
func (c *OutputDispatchClient) Get(ctx context.Context, id uuid.UUID) (*OutputDispatch, error) {
	return c.Query().Where(outputdispatch.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OutputDispatchClient) GetX(ctx context.Context, id uuid.UUID) *OutputDispatch {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OutputDispatchClient) Hooks() []Hook {
	return c.hooks.OutputDispatch
}

// Interceptors returns the client interceptors.
func (c *OutputDispatchClient) Interceptors() []Interceptor {
	return c.inters.OutputDispatch
}

func (c *OutputDispatchClient) mutate(ctx context.Context, m *OutputDispatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OutputDispatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OutputDispatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OutputDispatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OutputDispatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OutputDispatch mutation op: %q", m.Op())
	}
}

// OutputTaskClient is a client for the OutputTask schema.
type OutputTaskClient struct {
	config
}

// NewOutputTaskClient returns a client for the OutputTask from the given config.
func NewOutputTaskClient(c config) *OutputTaskClient {
	return &OutputTaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `outputtask.Hooks(f(g(h())))`.
func (c *OutputTaskClient) Use(hooks ...Hook) {
	c.hooks.OutputTask = append(c.hooks.OutputTask, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `outputtask.Intercept(f(g(h())))`.
func (c *OutputTaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.OutputTask = append(c.inters.OutputTask, interceptors...)
}

// Create returns a builder for creating a OutputTask entity.
func (c *OutputTaskClient) Create() *OutputTaskCreate {
	mutation := newOutputTaskMutation(c.config, OpCreate)
	return &OutputTaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OutputTask entities.
func (c *OutputTaskClient) CreateBulk(builders ...*OutputTaskCreate) *OutputTaskCreateBulk {
	return &OutputTaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OutputTaskClient) MapCreateBulk(slice any, setFunc func(*OutputTaskCreate, int)) *OutputTaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OutputTaskCreateBulk{err: fmt.Errorf("calling to OutputTaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OutputTaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OutputTaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OutputTask.
func (c *OutputTaskClient) Update() *OutputTaskUpdate {
	mutation := newOutputTaskMutation(c.config, OpUpdate)
	return &OutputTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OutputTaskClient) UpdateOne(_m *OutputTask) *OutputTaskUpdateOne {
	mutation := newOutputTaskMutation(c.config, OpUpdateOne, withOutputTask(_m))
	return &OutputTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OutputTaskClient) UpdateOneID(id uuid.UUID) *OutputTaskUpdateOne {
	mutation := newOutputTaskMutation(c.config, OpUpdateOne, withOutputTaskID(id))
	return &OutputTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OutputTask.
func (c *OutputTaskClient) Delete() *OutputTaskDelete {
	mutation := newOutputTaskMutation(c.config, OpDelete)
	return &OutputTaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OutputTaskClient) DeleteOne(_m *OutputTask) *OutputTaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OutputTaskClient) DeleteOneID(id uuid.UUID) *OutputTaskDeleteOne {
	builder := c.Delete().Where(outputtask.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OutputTaskDeleteOne{builder}
}

// Query returns a query builder for OutputTask.
func (c *OutputTaskClient) Query() *OutputTaskQuery {
	return &OutputTaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOutputTask},
		inters: c.Interceptors(),
	}
}

// Get returns a OutputTask entity by its id.
func (c *OutputTaskClient) Get(ctx context.Context, id uuid.UUID) (*OutputTask, error) {
	return c.Query().Where(outputtask.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OutputTaskClient) GetX(ctx context.Context, id uuid.UUID) *OutputTask {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OutputTaskClient) Hooks() []Hook {
	return c.hooks.OutputTask
}

// Interceptors returns the client interceptors.
func (c *OutputTaskClient) Interceptors() []Interceptor {
	return c.inters.OutputTask
}

func (c *OutputTaskClient) mutate(ctx context.Context, m *OutputTaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OutputTaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OutputTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OutputTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OutputTaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OutputTask mutation op: %q", m.Op())
	}
}

// RemindChannelClient is a client for the RemindChannel schema.
type RemindChannelClient struct {
	config
}

// NewRemindChannelClient returns a client for the RemindChannel from the given config.
func NewRemindChannelClient(c config) *RemindChannelClient {
	return &RemindChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `remindchannel.Hooks(f(g(h())))`.
func (c *RemindChannelClient) Use(hooks ...Hook) {
	c.hooks.RemindChannel = append(c.hooks.RemindChannel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `remindchannel.Intercept(f(g(h())))`.
func (c *RemindChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.RemindChannel = append(c.inters.RemindChannel, interceptors...)
}

// Create returns a builder for creating a RemindChannel entity.
func (c *RemindChannelClient) Create() *RemindChannelCreate {
	mutation := newRemindChannelMutation(c.config, OpCreate)
	return &RemindChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RemindChannel entities.
func (c *RemindChannelClient) CreateBulk(builders ...*RemindChannelCreate) *RemindChannelCreateBulk {
	return &RemindChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RemindChannelClient) MapCreateBulk(slice any, setFunc func(*RemindChannelCreate, int)) *RemindChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RemindChannelCreateBulk{err: fmt.Errorf("calling to RemindChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RemindChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RemindChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RemindChannel.
func (c *RemindChannelClient) Update() *RemindChannelUpdate {
	mutation := newRemindChannelMutation(c.config, OpUpdate)
	return &RemindChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RemindChannelClient) UpdateOne(_m *RemindChannel) *RemindChannelUpdateOne {
	mutation := newRemindChannelMutation(c.config, OpUpdateOne, withRemindChannel(_m))
	return &RemindChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RemindChannelClient) UpdateOneID(id string) *RemindChannelUpdateOne {
	mutation := newRemindChannelMutation(c.config, OpUpdateOne, withRemindChannelID(id))
	return &RemindChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RemindChannel.
func (c *RemindChannelClient) Delete() *RemindChannelDelete {
	mutation := newRemindChannelMutation(c.config, OpDelete)
	return &RemindChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RemindChannelClient) DeleteOne(_m *RemindChannel) *RemindChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RemindChannelClient) DeleteOneID(id string) *RemindChannelDeleteOne {
	builder := c.Delete().Where(remindchannel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RemindChannelDeleteOne{builder}
}

// Query returns a query builder for RemindChannel.
func (c *RemindChannelClient) Query() *RemindChannelQuery {
	return &RemindChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRemindChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a RemindChannel entity by its id.
func (c *RemindChannelClient) Get(ctx context.Context, id string) (*RemindChannel, error) {
	return c.Query().Where(remindchannel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RemindChannelClient) GetX(ctx context.Context, id string) *RemindChannel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RemindChannelClient) Hooks() []Hook {
	return c.hooks.RemindChannel
}

// Interceptors returns the client interceptors.
func (c *RemindChannelClient) Interceptors() []Interceptor {
	return c.inters.RemindChannel
}

func (c *RemindChannelClient) mutate(ctx context.Context, m *RemindChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RemindChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RemindChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RemindChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RemindChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RemindChannel mutation op: %q", m.Op())
	}
}

// RemindTaskClient is a client for the RemindTask schema.
type RemindTaskClient struct {
	config
}

// NewRemindTaskClient returns a client for the RemindTask from the given config.
func NewRemindTaskClient(c config) *RemindTaskClient {
	return &RemindTaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `remindtask.Hooks(f(g(h())))`.
func (c *RemindTaskClient) Use(hooks ...Hook) {
	c.hooks.RemindTask = append(c.hooks.RemindTask, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `remindtask.Intercept(f(g(h())))`.
func (c *RemindTaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.RemindTask = append(c.inters.RemindTask, interceptors...)
}

// Create returns a builder for creating a RemindTask entity.
func (c *RemindTaskClient) Create() *RemindTaskCreate {
	mutation := newRemindTaskMutation(c.config, OpCreate)
	return &RemindTaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RemindTask entities.
func (c *RemindTaskClient) CreateBulk(builders ...*RemindTaskCreate) *RemindTaskCreateBulk {
	return &RemindTaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RemindTaskClient) MapCreateBulk(slice any, setFunc func(*RemindTaskCreate, int)) *RemindTaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RemindTaskCreateBulk{err: fmt.Errorf("calling to RemindTaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RemindTaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RemindTaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RemindTask.
func (c *RemindTaskClient) Update() *RemindTaskUpdate {
	mutation := newRemindTaskMutation(c.config, OpUpdate)
	return &RemindTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RemindTaskClient) UpdateOne(_m *RemindTask) *RemindTaskUpdateOne {
	mutation := newRemindTaskMutation(c.config, OpUpdateOne, withRemindTask(_m))
	return &RemindTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RemindTaskClient) UpdateOneID(id uuid.UUID) *RemindTaskUpdateOne {
	mutation := newRemindTaskMutation(c.config, OpUpdateOne, withRemindTaskID(id))
	return &RemindTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RemindTask.
func (c *RemindTaskClient) Delete() *RemindTaskDelete {
	mutation := newRemindTaskMutation(c.config, OpDelete)
	return &RemindTaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RemindTaskClient) DeleteOne(_m *RemindTask) *RemindTaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RemindTaskClient) DeleteOneID(id uuid.UUID) *RemindTaskDeleteOne {
	builder := c.Delete().Where(remindtask.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RemindTaskDeleteOne{builder}
}

// Query returns a query builder for RemindTask.
func (c *RemindTaskClient) Query() *RemindTaskQuery {
	return &RemindTaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRemindTask},
		inters: c.Interceptors(),
	}
}

// Get returns a RemindTask entity by its id.
func (c *RemindTaskClient) Get(ctx context.Context, id uuid.UUID) (*RemindTask, error) {
	return c.Query().Where(remindtask.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RemindTaskClient) GetX(ctx context.Context, id uuid.UUID) *RemindTask {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RemindTaskClient) Hooks() []Hook {
	return c.hooks.RemindTask
}

// Interceptors returns the client interceptors.
func (c *RemindTaskClient) Interceptors() []Interceptor {
	return c.inters.RemindTask
}

func (c *RemindTaskClient) mutate(ctx context.Context, m *RemindTaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RemindTaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RemindTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RemindTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RemindTaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RemindTask mutation op: %q", m.Op())
	}
}

// RemindTaskInventoryItemClient is a client for the RemindTaskInventoryItem schema.
type RemindTaskInventoryItemClient struct {
	config
}

// NewRemindTaskInventoryItemClient returns a client for the RemindTaskInventoryItem from the given config.
func NewRemindTaskInventoryItemClient(c config) *RemindTaskInventoryItemClient {
	return &RemindTaskInventoryItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `remindtaskinventoryitem.Hooks(f(g(h())))`.
func (c *RemindTaskInventoryItemClient) Use(hooks ...Hook) {
	c.hooks.RemindTaskInventoryItem = append(c.hooks.RemindTaskInventoryItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `remindtaskinventoryitem.Intercept(f(g(h())))`.
func (c *RemindTaskInventoryItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.RemindTaskInventoryItem = append(c.inters.RemindTaskInventoryItem, interceptors...)
}

// Create returns a builder for creating a RemindTaskInventoryItem entity.
func (c *RemindTaskInventoryItemClient) Create() *RemindTaskInventoryItemCreate {
	mutation := newRemindTaskInventoryItemMutation(c.config, OpCreate)
	return &RemindTaskInventoryItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RemindTaskInventoryItem entities.
func (c *RemindTaskInventoryItemClient) CreateBulk(builders ...*RemindTaskInventoryItemCreate) *RemindTaskInventoryItemCreateBulk {
	return &RemindTaskInventoryItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RemindTaskInventoryItemClient) MapCreateBulk(slice any, setFunc func(*RemindTaskInventoryItemCreate, int)) *RemindTaskInventoryItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RemindTaskInventoryItemCreateBulk{err: fmt.Errorf("calling to RemindTaskInventoryItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RemindTaskInventoryItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RemindTaskInventoryItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RemindTaskInventoryItem.
func (c *RemindTaskInventoryItemClient) Update() *RemindTaskInventoryItemUpdate {
	mutation := newRemindTaskInventoryItemMutation(c.config, OpUpdate)
	return &RemindTaskInventoryItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RemindTaskInventoryItemClient) UpdateOne(_m *RemindTaskInventoryItem) *RemindTaskInventoryItemUpdateOne {
	mutation := newRemindTaskInventoryItemMutation(c.config, OpUpdateOne, withRemindTaskInventoryItem(_m))
	return &RemindTaskInventoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RemindTaskInventoryItemClient) UpdateOneID(id uuid.UUID) *RemindTaskInventoryItemUpdateOne {
	mutation := newRemindTaskInventoryItemMutation(c.config, OpUpdateOne, withRemindTaskInventoryItemID(id))
	return &RemindTaskInventoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RemindTaskInventoryItem.
func (c *RemindTaskInventoryItemClient) Delete() *RemindTaskInventoryItemDelete {
	mutation := newRemindTaskInventoryItemMutation(c.config, OpDelete)
	return &RemindTaskInventoryItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RemindTaskInventoryItemClient) DeleteOne(_m *RemindTaskInventoryItem) *RemindTaskInventoryItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RemindTaskInventoryItemClient) DeleteOneID(id uuid.UUID) *RemindTaskInventoryItemDeleteOne {
	builder := c.Delete().Where(remindtaskinventoryitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RemindTaskInventoryItemDeleteOne{builder}
}

// Query returns a query builder for RemindTaskInventoryItem.
func (c *RemindTaskInventoryItemClient) Query() *RemindTaskInventoryItemQuery {
	return &RemindTaskInventoryItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRemindTaskInventoryItem},
		inters: c.Interceptors(),
	}
}

// Get returns a RemindTaskInventoryItem entity by its id.
func (c *RemindTaskInventoryItemClient) Get(ctx context.Context, id uuid.UUID) (*RemindTaskInventoryItem, error) {
	return c.Query().Where(remindtaskinventoryitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RemindTaskInventoryItemClient) GetX(ctx context.Context, id uuid.UUID) *RemindTaskInventoryItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RemindTaskInventoryItemClient) Hooks() []Hook {
	return c.hooks.RemindTaskInventoryItem
}

// Interceptors returns the client interceptors.
func (c *RemindTaskInventoryItemClient) Interceptors() []Interceptor {
	return c.inters.RemindTaskInventoryItem
}

func (c *RemindTaskInventoryItemClient) mutate(ctx context.Context, m *RemindTaskInventoryItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RemindTaskInventoryItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RemindTaskInventoryItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RemindTaskInventoryItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RemindTaskInventoryItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RemindTaskInventoryItem mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ChannelOutputSuspension, DiscordCardView, InventoryChannel, InventoryItem,
		ListChannel, ListItem, OperationRecord, OutputDispatch, OutputTask,
		RemindChannel, RemindTask, RemindTaskInventoryItem []ent.Hook
	}
	inters struct {
		ChannelOutputSuspension, DiscordCardView, InventoryChannel, InventoryItem,
		ListChannel, ListItem, OperationRecord, OutputDispatch, OutputTask,
		RemindChannel, RemindTask, RemindTaskInventoryItem []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
