// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/discordcardview"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// DiscordCardViewUpdate is the builder for updating DiscordCardView entities.
type DiscordCardViewUpdate struct {
	config
	hooks    []Hook
	mutation *DiscordCardViewMutation
}

// Where appends a list predicates to the DiscordCardViewUpdate builder.
func (_u *DiscordCardViewUpdate) Where(ps ...predicate.DiscordCardView) *DiscordCardViewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *DiscordCardViewUpdate) SetChannelID(v string) *DiscordCardViewUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *DiscordCardViewUpdate) SetNillableChannelID(v *string) *DiscordCardViewUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetTargetKind sets the "target_kind" field.
func (_u *DiscordCardViewUpdate) SetTargetKind(v string) *DiscordCardViewUpdate {
	_u.mutation.SetTargetKind(v)
	return _u
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_u *DiscordCardViewUpdate) SetNillableTargetKind(v *string) *DiscordCardViewUpdate {
	if v != nil {
		_u.SetTargetKind(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *DiscordCardViewUpdate) SetTargetID(v string) *DiscordCardViewUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *DiscordCardViewUpdate) SetNillableTargetID(v *string) *DiscordCardViewUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *DiscordCardViewUpdate) SetMode(v string) *DiscordCardViewUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *DiscordCardViewUpdate) SetNillableMode(v *string) *DiscordCardViewUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPage sets the "page" field.
func (_u *DiscordCardViewUpdate) SetPage(v int) *DiscordCardViewUpdate {
	_u.mutation.ResetPage()
	_u.mutation.SetPage(v)
	return _u
}

// SetNillablePage sets the "page" field if the given value is not nil.
func (_u *DiscordCardViewUpdate) SetNillablePage(v *int) *DiscordCardViewUpdate {
	if v != nil {
		_u.SetPage(*v)
	}
	return _u
}

// AddPage adds value to the "page" field.
func (_u *DiscordCardViewUpdate) AddPage(v int) *DiscordCardViewUpdate {
	_u.mutation.AddPage(v)
	return _u
}

// SetViewVersion sets the "view_version" field.
func (_u *DiscordCardViewUpdate) SetViewVersion(v int64) *DiscordCardViewUpdate {
	_u.mutation.ResetViewVersion()
	_u.mutation.SetViewVersion(v)
	return _u
}

// SetNillableViewVersion sets the "view_version" field if the given value is not nil.
func (_u *DiscordCardViewUpdate) SetNillableViewVersion(v *int64) *DiscordCardViewUpdate {
	if v != nil {
		_u.SetViewVersion(*v)
	}
	return _u
}

// AddViewVersion adds value to the "view_version" field.
func (_u *DiscordCardViewUpdate) AddViewVersion(v int64) *DiscordCardViewUpdate {
	_u.mutation.AddViewVersion(v)
	return _u
}

// Mutation returns the DiscordCardViewMutation object of the builder.
func (_u *DiscordCardViewUpdate) Mutation() *DiscordCardViewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscordCardViewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordCardViewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscordCardViewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordCardViewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordCardViewUpdate) check() error {
	if v, ok := _u.mutation.Page(); ok {
		if err := discordcardview.PageValidator(v); err != nil {
			return &ValidationError{Name: "page", err: fmt.Errorf(`ent: validator failed for field "DiscordCardView.page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewVersion(); ok {
		if err := discordcardview.ViewVersionValidator(v); err != nil {
			return &ValidationError{Name: "view_version", err: fmt.Errorf(`ent: validator failed for field "DiscordCardView.view_version": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscordCardViewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordcardview.Table, discordcardview.Columns, sqlgraph.NewFieldSpec(discordcardview.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(discordcardview.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetKind(); ok {
		_spec.SetField(discordcardview.FieldTargetKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(discordcardview.FieldTargetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(discordcardview.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Page(); ok {
		_spec.SetField(discordcardview.FieldPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPage(); ok {
		_spec.AddField(discordcardview.FieldPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewVersion(); ok {
		_spec.SetField(discordcardview.FieldViewVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedViewVersion(); ok {
		_spec.AddField(discordcardview.FieldViewVersion, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordcardview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscordCardViewUpdateOne is the builder for updating a single DiscordCardView entity.
type DiscordCardViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscordCardViewMutation
}

// SetChannelID sets the "channel_id" field.
func (_u *DiscordCardViewUpdateOne) SetChannelID(v string) *DiscordCardViewUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *DiscordCardViewUpdateOne) SetNillableChannelID(v *string) *DiscordCardViewUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetTargetKind sets the "target_kind" field.
func (_u *DiscordCardViewUpdateOne) SetTargetKind(v string) *DiscordCardViewUpdateOne {
	_u.mutation.SetTargetKind(v)
	return _u
}

// SetNillableTargetKind sets the "target_kind" field if the given value is not nil.
func (_u *DiscordCardViewUpdateOne) SetNillableTargetKind(v *string) *DiscordCardViewUpdateOne {
	if v != nil {
		_u.SetTargetKind(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *DiscordCardViewUpdateOne) SetTargetID(v string) *DiscordCardViewUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *DiscordCardViewUpdateOne) SetNillableTargetID(v *string) *DiscordCardViewUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *DiscordCardViewUpdateOne) SetMode(v string) *DiscordCardViewUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *DiscordCardViewUpdateOne) SetNillableMode(v *string) *DiscordCardViewUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPage sets the "page" field.
func (_u *DiscordCardViewUpdateOne) SetPage(v int) *DiscordCardViewUpdateOne {
	_u.mutation.ResetPage()
	_u.mutation.SetPage(v)
	return _u
}

// SetNillablePage sets the "page" field if the given value is not nil.
func (_u *DiscordCardViewUpdateOne) SetNillablePage(v *int) *DiscordCardViewUpdateOne {
	if v != nil {
		_u.SetPage(*v)
	}
	return _u
}

// AddPage adds value to the "page" field.
func (_u *DiscordCardViewUpdateOne) AddPage(v int) *DiscordCardViewUpdateOne {
	_u.mutation.AddPage(v)
	return _u
}

// SetViewVersion sets the "view_version" field.
func (_u *DiscordCardViewUpdateOne) SetViewVersion(v int64) *DiscordCardViewUpdateOne {
	_u.mutation.ResetViewVersion()
	_u.mutation.SetViewVersion(v)
	return _u
}

// SetNillableViewVersion sets the "view_version" field if the given value is not nil.
func (_u *DiscordCardViewUpdateOne) SetNillableViewVersion(v *int64) *DiscordCardViewUpdateOne {
	if v != nil {
		_u.SetViewVersion(*v)
	}
	return _u
}

// AddViewVersion adds value to the "view_version" field.
func (_u *DiscordCardViewUpdateOne) AddViewVersion(v int64) *DiscordCardViewUpdateOne {
	_u.mutation.AddViewVersion(v)
	return _u
}

// Mutation returns the DiscordCardViewMutation object of the builder.
func (_u *DiscordCardViewUpdateOne) Mutation() *DiscordCardViewMutation {
	return _u.mutation
}

// Where appends a list predicates to the DiscordCardViewUpdate builder.
func (_u *DiscordCardViewUpdateOne) Where(ps ...predicate.DiscordCardView) *DiscordCardViewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscordCardViewUpdateOne) Select(field string, fields ...string) *DiscordCardViewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscordCardView entity.
func (_u *DiscordCardViewUpdateOne) Save(ctx context.Context) (*DiscordCardView, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscordCardViewUpdateOne) SaveX(ctx context.Context) *DiscordCardView {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscordCardViewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscordCardViewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscordCardViewUpdateOne) check() error {
	if v, ok := _u.mutation.Page(); ok {
		if err := discordcardview.PageValidator(v); err != nil {
			return &ValidationError{Name: "page", err: fmt.Errorf(`ent: validator failed for field "DiscordCardView.page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewVersion(); ok {
		if err := discordcardview.ViewVersionValidator(v); err != nil {
			return &ValidationError{Name: "view_version", err: fmt.Errorf(`ent: validator failed for field "DiscordCardView.view_version": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscordCardViewUpdateOne) sqlSave(ctx context.Context) (_node *DiscordCardView, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discordcardview.Table, discordcardview.Columns, sqlgraph.NewFieldSpec(discordcardview.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscordCardView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordcardview.FieldID)
		for _, f := range fields {
			if !discordcardview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discordcardview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(discordcardview.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetKind(); ok {
		_spec.SetField(discordcardview.FieldTargetKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(discordcardview.FieldTargetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(discordcardview.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Page(); ok {
		_spec.SetField(discordcardview.FieldPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPage(); ok {
		_spec.AddField(discordcardview.FieldPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewVersion(); ok {
		_spec.SetField(discordcardview.FieldViewVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedViewVersion(); ok {
		_spec.AddField(discordcardview.FieldViewVersion, field.TypeInt64, value)
	}
	_node = &DiscordCardView{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discordcardview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
