// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/inventoryitem"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// InventoryItemUpdate is the builder for updating InventoryItem entities.
type InventoryItemUpdate struct {
	config
	hooks    []Hook
	mutation *InventoryItemMutation
}

// Where appends a list predicates to the InventoryItemUpdate builder.
func (_u *InventoryItemUpdate) Where(ps ...predicate.InventoryItem) *InventoryItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLegacyID sets the "legacy_id" field.
func (_u *InventoryItemUpdate) SetLegacyID(v string) *InventoryItemUpdate {
	_u.mutation.SetLegacyID(v)
	return _u
}

// SetNillableLegacyID sets the "legacy_id" field if the given value is not nil.
func (_u *InventoryItemUpdate) SetNillableLegacyID(v *string) *InventoryItemUpdate {
	if v != nil {
		_u.SetLegacyID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *InventoryItemUpdate) SetChannelID(v string) *InventoryItemUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *InventoryItemUpdate) SetNillableChannelID(v *string) *InventoryItemUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *InventoryItemUpdate) SetName(v string) *InventoryItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InventoryItemUpdate) SetNillableName(v *string) *InventoryItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStock sets the "stock" field.
func (_u *InventoryItemUpdate) SetStock(v string) *InventoryItemUpdate {
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *InventoryItemUpdate) SetNillableStock(v *string) *InventoryItemUpdate {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *InventoryItemUpdate) SetCategory(v string) *InventoryItemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *InventoryItemUpdate) SetNillableCategory(v *string) *InventoryItemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *InventoryItemUpdate) ClearCategory() *InventoryItemUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetPosition sets the "position" field.
func (_u *InventoryItemUpdate) SetPosition(v int) *InventoryItemUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *InventoryItemUpdate) SetNillablePosition(v *int) *InventoryItemUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *InventoryItemUpdate) AddPosition(v int) *InventoryItemUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the InventoryItemMutation object of the builder.
func (_u *InventoryItemUpdate) Mutation() *InventoryItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InventoryItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventoryItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InventoryItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventoryItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InventoryItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(inventoryitem.Table, inventoryitem.Columns, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LegacyID(); ok {
		_spec.SetField(inventoryitem.FieldLegacyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(inventoryitem.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(inventoryitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(inventoryitem.FieldStock, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(inventoryitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(inventoryitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(inventoryitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(inventoryitem.FieldPosition, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InventoryItemUpdateOne is the builder for updating a single InventoryItem entity.
type InventoryItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InventoryItemMutation
}

// SetLegacyID sets the "legacy_id" field.
func (_u *InventoryItemUpdateOne) SetLegacyID(v string) *InventoryItemUpdateOne {
	_u.mutation.SetLegacyID(v)
	return _u
}

// SetNillableLegacyID sets the "legacy_id" field if the given value is not nil.
func (_u *InventoryItemUpdateOne) SetNillableLegacyID(v *string) *InventoryItemUpdateOne {
	if v != nil {
		_u.SetLegacyID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *InventoryItemUpdateOne) SetChannelID(v string) *InventoryItemUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *InventoryItemUpdateOne) SetNillableChannelID(v *string) *InventoryItemUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *InventoryItemUpdateOne) SetName(v string) *InventoryItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InventoryItemUpdateOne) SetNillableName(v *string) *InventoryItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStock sets the "stock" field.
func (_u *InventoryItemUpdateOne) SetStock(v string) *InventoryItemUpdateOne {
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *InventoryItemUpdateOne) SetNillableStock(v *string) *InventoryItemUpdateOne {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *InventoryItemUpdateOne) SetCategory(v string) *InventoryItemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *InventoryItemUpdateOne) SetNillableCategory(v *string) *InventoryItemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *InventoryItemUpdateOne) ClearCategory() *InventoryItemUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetPosition sets the "position" field.
func (_u *InventoryItemUpdateOne) SetPosition(v int) *InventoryItemUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *InventoryItemUpdateOne) SetNillablePosition(v *int) *InventoryItemUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *InventoryItemUpdateOne) AddPosition(v int) *InventoryItemUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the InventoryItemMutation object of the builder.
func (_u *InventoryItemUpdateOne) Mutation() *InventoryItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the InventoryItemUpdate builder.
func (_u *InventoryItemUpdateOne) Where(ps ...predicate.InventoryItem) *InventoryItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InventoryItemUpdateOne) Select(field string, fields ...string) *InventoryItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InventoryItem entity.
func (_u *InventoryItemUpdateOne) Save(ctx context.Context) (*InventoryItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventoryItemUpdateOne) SaveX(ctx context.Context) *InventoryItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InventoryItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventoryItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InventoryItemUpdateOne) sqlSave(ctx context.Context) (_node *InventoryItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(inventoryitem.Table, inventoryitem.Columns, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InventoryItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inventoryitem.FieldID)
		for _, f := range fields {
			if !inventoryitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inventoryitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LegacyID(); ok {
		_spec.SetField(inventoryitem.FieldLegacyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(inventoryitem.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(inventoryitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(inventoryitem.FieldStock, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(inventoryitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(inventoryitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(inventoryitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(inventoryitem.FieldPosition, field.TypeInt, value)
	}
	_node = &InventoryItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
