// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/inventoryitem"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// InventoryItemDelete is the builder for deleting a InventoryItem entity.
type InventoryItemDelete struct {
	config
	hooks    []Hook
	mutation *InventoryItemMutation
}

// Where appends a list predicates to the InventoryItemDelete builder.
func (_d *InventoryItemDelete) Where(ps ...predicate.InventoryItem) *InventoryItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InventoryItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InventoryItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InventoryItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(inventoryitem.Table, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InventoryItemDeleteOne is the builder for deleting a single InventoryItem entity.
type InventoryItemDeleteOne struct {
	_d *InventoryItemDelete
}

// Where appends a list predicates to the InventoryItemDelete builder.
func (_d *InventoryItemDeleteOne) Where(ps ...predicate.InventoryItem) *InventoryItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InventoryItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{inventoryitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InventoryItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
