// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/inventoryitem"
)

// InventoryItemCreate is the builder for creating a InventoryItem entity.
type InventoryItemCreate struct {
	config
	mutation *InventoryItemMutation
	hooks    []Hook
}

// SetLegacyID sets the "legacy_id" field.
func (_c *InventoryItemCreate) SetLegacyID(v string) *InventoryItemCreate {
	_c.mutation.SetLegacyID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *InventoryItemCreate) SetChannelID(v string) *InventoryItemCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *InventoryItemCreate) SetName(v string) *InventoryItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStock sets the "stock" field.
func (_c *InventoryItemCreate) SetStock(v string) *InventoryItemCreate {
	_c.mutation.SetStock(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *InventoryItemCreate) SetCategory(v string) *InventoryItemCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *InventoryItemCreate) SetNillableCategory(v *string) *InventoryItemCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *InventoryItemCreate) SetPosition(v int) *InventoryItemCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetID sets the "id" field.
func (_c *InventoryItemCreate) SetID(v uuid.UUID) *InventoryItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InventoryItemMutation object of the builder.
func (_c *InventoryItemCreate) Mutation() *InventoryItemMutation {
	return _c.mutation
}

// Save creates the InventoryItem in the database.
func (_c *InventoryItemCreate) Save(ctx context.Context) (*InventoryItem, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryItemCreate) SaveX(ctx context.Context) *InventoryItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryItemCreate) check() error {
	if _, ok := _c.mutation.LegacyID(); !ok {
		return &ValidationError{Name: "legacy_id", err: errors.New(`ent: missing required field "InventoryItem.legacy_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "InventoryItem.channel_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "InventoryItem.name"`)}
	}
	if _, ok := _c.mutation.Stock(); !ok {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required field "InventoryItem.stock"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "InventoryItem.position"`)}
	}
	return nil
}

func (_c *InventoryItemCreate) sqlSave(ctx context.Context) (*InventoryItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryItemCreate) createSpec() (*InventoryItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InventoryItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventoryitem.Table, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LegacyID(); ok {
		_spec.SetField(inventoryitem.FieldLegacyID, field.TypeString, value)
		_node.LegacyID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(inventoryitem.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(inventoryitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Stock(); ok {
		_spec.SetField(inventoryitem.FieldStock, field.TypeString, value)
		_node.Stock = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(inventoryitem.FieldCategory, field.TypeString, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(inventoryitem.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	return _node, _spec
}

// InventoryItemCreateBulk is the builder for creating many InventoryItem entities in bulk.
type InventoryItemCreateBulk struct {
	config
	err      error
	builders []*InventoryItemCreate
}

// Save creates the InventoryItem entities in the database.
func (_c *InventoryItemCreateBulk) Save(ctx context.Context) ([]*InventoryItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InventoryItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryItemCreateBulk) SaveX(ctx context.Context) []*InventoryItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
