// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/inventorychannel"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// InventoryChannelDelete is the builder for deleting a InventoryChannel entity.
type InventoryChannelDelete struct {
	config
	hooks    []Hook
	mutation *InventoryChannelMutation
}

// Where appends a list predicates to the InventoryChannelDelete builder.
func (_d *InventoryChannelDelete) Where(ps ...predicate.InventoryChannel) *InventoryChannelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InventoryChannelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InventoryChannelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InventoryChannelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(inventorychannel.Table, sqlgraph.NewFieldSpec(inventorychannel.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InventoryChannelDeleteOne is the builder for deleting a single InventoryChannel entity.
type InventoryChannelDeleteOne struct {
	_d *InventoryChannelDelete
}

// Where appends a list predicates to the InventoryChannelDelete builder.
func (_d *InventoryChannelDeleteOne) Where(ps ...predicate.InventoryChannel) *InventoryChannelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InventoryChannelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{inventorychannel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InventoryChannelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
