// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/listchannel"
)

// ListChannelCreate is the builder for creating a ListChannel entity.
type ListChannelCreate struct {
	config
	mutation *ListChannelMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (_c *ListChannelCreate) SetMessageID(v string) *ListChannelCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *ListChannelCreate) SetNillableMessageID(v *string) *ListChannelCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetListTitle sets the "list_title" field.
func (_c *ListChannelCreate) SetListTitle(v string) *ListChannelCreate {
	_c.mutation.SetListTitle(v)
	return _c
}

// SetOperationLogThreadID sets the "operation_log_thread_id" field.
func (_c *ListChannelCreate) SetOperationLogThreadID(v string) *ListChannelCreate {
	_c.mutation.SetOperationLogThreadID(v)
	return _c
}

// SetNillableOperationLogThreadID sets the "operation_log_thread_id" field if the given value is not nil.
func (_c *ListChannelCreate) SetNillableOperationLogThreadID(v *string) *ListChannelCreate {
	if v != nil {
		_c.SetOperationLogThreadID(*v)
	}
	return _c
}

// SetDefaultCategory sets the "default_category" field.
func (_c *ListChannelCreate) SetDefaultCategory(v string) *ListChannelCreate {
	_c.mutation.SetDefaultCategory(v)
	return _c
}

// SetNillableDefaultCategory sets the "default_category" field if the given value is not nil.
func (_c *ListChannelCreate) SetNillableDefaultCategory(v *string) *ListChannelCreate {
	if v != nil {
		_c.SetDefaultCategory(*v)
	}
	return _c
}

// SetEditVersion sets the "edit_version" field.
func (_c *ListChannelCreate) SetEditVersion(v int64) *ListChannelCreate {
	_c.mutation.SetEditVersion(v)
	return _c
}

// SetNillableEditVersion sets the "edit_version" field if the given value is not nil.
func (_c *ListChannelCreate) SetNillableEditVersion(v *int64) *ListChannelCreate {
	if v != nil {
		_c.SetEditVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ListChannelCreate) SetID(v string) *ListChannelCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ListChannelMutation object of the builder.
func (_c *ListChannelCreate) Mutation() *ListChannelMutation {
	return _c.mutation
}

// Save creates the ListChannel in the database.
func (_c *ListChannelCreate) Save(ctx context.Context) (*ListChannel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListChannelCreate) SaveX(ctx context.Context) *ListChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListChannelCreate) defaults() {
	if _, ok := _c.mutation.DefaultCategory(); !ok {
		v := listchannel.DefaultDefaultCategory
		_c.mutation.SetDefaultCategory(v)
	}
	if _, ok := _c.mutation.EditVersion(); !ok {
		v := listchannel.DefaultEditVersion
		_c.mutation.SetEditVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListChannelCreate) check() error {
	if _, ok := _c.mutation.ListTitle(); !ok {
		return &ValidationError{Name: "list_title", err: errors.New(`ent: missing required field "ListChannel.list_title"`)}
	}
	if _, ok := _c.mutation.DefaultCategory(); !ok {
		return &ValidationError{Name: "default_category", err: errors.New(`ent: missing required field "ListChannel.default_category"`)}
	}
	if _, ok := _c.mutation.EditVersion(); !ok {
		return &ValidationError{Name: "edit_version", err: errors.New(`ent: missing required field "ListChannel.edit_version"`)}
	}
	return nil
}

func (_c *ListChannelCreate) sqlSave(ctx context.Context) (*ListChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ListChannel.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListChannelCreate) createSpec() (*ListChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &ListChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listchannel.Table, sqlgraph.NewFieldSpec(listchannel.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(listchannel.FieldMessageID, field.TypeString, value)
		_node.MessageID = &value
	}
	if value, ok := _c.mutation.ListTitle(); ok {
		_spec.SetField(listchannel.FieldListTitle, field.TypeString, value)
		_node.ListTitle = value
	}
	if value, ok := _c.mutation.OperationLogThreadID(); ok {
		_spec.SetField(listchannel.FieldOperationLogThreadID, field.TypeString, value)
		_node.OperationLogThreadID = &value
	}
	if value, ok := _c.mutation.DefaultCategory(); ok {
		_spec.SetField(listchannel.FieldDefaultCategory, field.TypeString, value)
		_node.DefaultCategory = value
	}
	if value, ok := _c.mutation.EditVersion(); ok {
		_spec.SetField(listchannel.FieldEditVersion, field.TypeInt64, value)
		_node.EditVersion = value
	}
	return _node, _spec
}

// ListChannelCreateBulk is the builder for creating many ListChannel entities in bulk.
type ListChannelCreateBulk struct {
	config
	err      error
	builders []*ListChannelCreate
}

// Save creates the ListChannel entities in the database.
func (_c *ListChannelCreateBulk) Save(ctx context.Context) ([]*ListChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ListChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListChannelCreateBulk) SaveX(ctx context.Context) []*ListChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
