// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/listitem"
)

// ListItemCreate is the builder for creating a ListItem entity.
type ListItemCreate struct {
	config
	mutation *ListItemMutation
	hooks    []Hook
}

// SetChannelID sets the "channel_id" field.
func (_c *ListItemCreate) SetChannelID(v string) *ListItemCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ListItemCreate) SetName(v string) *ListItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *ListItemCreate) SetCategory(v string) *ListItemCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ListItemCreate) SetNillableCategory(v *string) *ListItemCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetUntil sets the "until" field.
func (_c *ListItemCreate) SetUntil(v time.Time) *ListItemCreate {
	_c.mutation.SetUntil(v)
	return _c
}

// SetNillableUntil sets the "until" field if the given value is not nil.
func (_c *ListItemCreate) SetNillableUntil(v *time.Time) *ListItemCreate {
	if v != nil {
		_c.SetUntil(*v)
	}
	return _c
}

// SetIsCompleted sets the "is_completed" field.
func (_c *ListItemCreate) SetIsCompleted(v bool) *ListItemCreate {
	_c.mutation.SetIsCompleted(v)
	return _c
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_c *ListItemCreate) SetNillableIsCompleted(v *bool) *ListItemCreate {
	if v != nil {
		_c.SetIsCompleted(*v)
	}
	return _c
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_c *ListItemCreate) SetLastNotifiedAt(v time.Time) *ListItemCreate {
	_c.mutation.SetLastNotifiedAt(v)
	return _c
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_c *ListItemCreate) SetNillableLastNotifiedAt(v *time.Time) *ListItemCreate {
	if v != nil {
		_c.SetLastNotifiedAt(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *ListItemCreate) SetPosition(v int) *ListItemCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ListItemCreate) SetID(v uuid.UUID) *ListItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ListItemMutation object of the builder.
func (_c *ListItemCreate) Mutation() *ListItemMutation {
	return _c.mutation
}

// Save creates the ListItem in the database.
func (_c *ListItemCreate) Save(ctx context.Context) (*ListItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListItemCreate) SaveX(ctx context.Context) *ListItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListItemCreate) defaults() {
	if _, ok := _c.mutation.IsCompleted(); !ok {
		v := listitem.DefaultIsCompleted
		_c.mutation.SetIsCompleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListItemCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ListItem.channel_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ListItem.name"`)}
	}
	if _, ok := _c.mutation.IsCompleted(); !ok {
		return &ValidationError{Name: "is_completed", err: errors.New(`ent: missing required field "ListItem.is_completed"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "ListItem.position"`)}
	}
	return nil
}

func (_c *ListItemCreate) sqlSave(ctx context.Context) (*ListItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListItemCreate) createSpec() (*ListItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ListItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listitem.Table, sqlgraph.NewFieldSpec(listitem.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(listitem.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(listitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(listitem.FieldCategory, field.TypeString, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.Until(); ok {
		_spec.SetField(listitem.FieldUntil, field.TypeTime, value)
		_node.Until = &value
	}
	if value, ok := _c.mutation.IsCompleted(); ok {
		_spec.SetField(listitem.FieldIsCompleted, field.TypeBool, value)
		_node.IsCompleted = value
	}
	if value, ok := _c.mutation.LastNotifiedAt(); ok {
		_spec.SetField(listitem.FieldLastNotifiedAt, field.TypeTime, value)
		_node.LastNotifiedAt = &value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(listitem.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	return _node, _spec
}

// ListItemCreateBulk is the builder for creating many ListItem entities in bulk.
type ListItemCreateBulk struct {
	config
	err      error
	builders []*ListItemCreate
}

// Save creates the ListItem entities in the database.
func (_c *ListItemCreateBulk) Save(ctx context.Context) ([]*ListItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ListItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListItemCreateBulk) SaveX(ctx context.Context) []*ListItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
