// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/listitem"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ListItemUpdate is the builder for updating ListItem entities.
type ListItemUpdate struct {
	config
	hooks    []Hook
	mutation *ListItemMutation
}

// Where appends a list predicates to the ListItemUpdate builder.
func (_u *ListItemUpdate) Where(ps ...predicate.ListItem) *ListItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ListItemUpdate) SetChannelID(v string) *ListItemUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillableChannelID(v *string) *ListItemUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ListItemUpdate) SetName(v string) *ListItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillableName(v *string) *ListItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ListItemUpdate) SetCategory(v string) *ListItemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillableCategory(v *string) *ListItemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ListItemUpdate) ClearCategory() *ListItemUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetUntil sets the "until" field.
func (_u *ListItemUpdate) SetUntil(v time.Time) *ListItemUpdate {
	_u.mutation.SetUntil(v)
	return _u
}

// SetNillableUntil sets the "until" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillableUntil(v *time.Time) *ListItemUpdate {
	if v != nil {
		_u.SetUntil(*v)
	}
	return _u
}

// ClearUntil clears the value of the "until" field.
func (_u *ListItemUpdate) ClearUntil() *ListItemUpdate {
	_u.mutation.ClearUntil()
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *ListItemUpdate) SetIsCompleted(v bool) *ListItemUpdate {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillableIsCompleted(v *bool) *ListItemUpdate {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *ListItemUpdate) SetLastNotifiedAt(v time.Time) *ListItemUpdate {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillableLastNotifiedAt(v *time.Time) *ListItemUpdate {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (_u *ListItemUpdate) ClearLastNotifiedAt() *ListItemUpdate {
	_u.mutation.ClearLastNotifiedAt()
	return _u
}

// SetPosition sets the "position" field.
func (_u *ListItemUpdate) SetPosition(v int) *ListItemUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ListItemUpdate) SetNillablePosition(v *int) *ListItemUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *ListItemUpdate) AddPosition(v int) *ListItemUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the ListItemMutation object of the builder.
func (_u *ListItemUpdate) Mutation() *ListItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ListItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ListItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ListItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(listitem.Table, listitem.Columns, sqlgraph.NewFieldSpec(listitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(listitem.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(listitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(listitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(listitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Until(); ok {
		_spec.SetField(listitem.FieldUntil, field.TypeTime, value)
	}
	if _u.mutation.UntilCleared() {
		_spec.ClearField(listitem.FieldUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(listitem.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(listitem.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(listitem.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(listitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(listitem.FieldPosition, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ListItemUpdateOne is the builder for updating a single ListItem entity.
type ListItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ListItemMutation
}

// SetChannelID sets the "channel_id" field.
func (_u *ListItemUpdateOne) SetChannelID(v string) *ListItemUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillableChannelID(v *string) *ListItemUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ListItemUpdateOne) SetName(v string) *ListItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillableName(v *string) *ListItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ListItemUpdateOne) SetCategory(v string) *ListItemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillableCategory(v *string) *ListItemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ListItemUpdateOne) ClearCategory() *ListItemUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetUntil sets the "until" field.
func (_u *ListItemUpdateOne) SetUntil(v time.Time) *ListItemUpdateOne {
	_u.mutation.SetUntil(v)
	return _u
}

// SetNillableUntil sets the "until" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillableUntil(v *time.Time) *ListItemUpdateOne {
	if v != nil {
		_u.SetUntil(*v)
	}
	return _u
}

// ClearUntil clears the value of the "until" field.
func (_u *ListItemUpdateOne) ClearUntil() *ListItemUpdateOne {
	_u.mutation.ClearUntil()
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *ListItemUpdateOne) SetIsCompleted(v bool) *ListItemUpdateOne {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillableIsCompleted(v *bool) *ListItemUpdateOne {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *ListItemUpdateOne) SetLastNotifiedAt(v time.Time) *ListItemUpdateOne {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillableLastNotifiedAt(v *time.Time) *ListItemUpdateOne {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (_u *ListItemUpdateOne) ClearLastNotifiedAt() *ListItemUpdateOne {
	_u.mutation.ClearLastNotifiedAt()
	return _u
}

// SetPosition sets the "position" field.
func (_u *ListItemUpdateOne) SetPosition(v int) *ListItemUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ListItemUpdateOne) SetNillablePosition(v *int) *ListItemUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *ListItemUpdateOne) AddPosition(v int) *ListItemUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the ListItemMutation object of the builder.
func (_u *ListItemUpdateOne) Mutation() *ListItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ListItemUpdate builder.
func (_u *ListItemUpdateOne) Where(ps ...predicate.ListItem) *ListItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ListItemUpdateOne) Select(field string, fields ...string) *ListItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ListItem entity.
func (_u *ListItemUpdateOne) Save(ctx context.Context) (*ListItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListItemUpdateOne) SaveX(ctx context.Context) *ListItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ListItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ListItemUpdateOne) sqlSave(ctx context.Context) (_node *ListItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(listitem.Table, listitem.Columns, sqlgraph.NewFieldSpec(listitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ListItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listitem.FieldID)
		for _, f := range fields {
			if !listitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != listitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(listitem.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(listitem.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(listitem.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(listitem.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Until(); ok {
		_spec.SetField(listitem.FieldUntil, field.TypeTime, value)
	}
	if _u.mutation.UntilCleared() {
		_spec.ClearField(listitem.FieldUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(listitem.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(listitem.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(listitem.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(listitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(listitem.FieldPosition, field.TypeInt, value)
	}
	_node = &ListItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
