// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/listchannel"
)

// ListChannel is the model entity for the ListChannel schema.
type ListChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID *string `json:"message_id,omitempty"`
	// ListTitle holds the value of the "list_title" field.
	ListTitle string `json:"list_title,omitempty"`
	// OperationLogThreadID holds the value of the "operation_log_thread_id" field.
	OperationLogThreadID *string `json:"operation_log_thread_id,omitempty"`
	// DefaultCategory holds the value of the "default_category" field.
	DefaultCategory string `json:"default_category,omitempty"`
	// EditVersion holds the value of the "edit_version" field.
	EditVersion  int64 `json:"edit_version,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ListChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case listchannel.FieldEditVersion:
			values[i] = new(sql.NullInt64)
		case listchannel.FieldID, listchannel.FieldMessageID, listchannel.FieldListTitle, listchannel.FieldOperationLogThreadID, listchannel.FieldDefaultCategory:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ListChannel fields.
func (_m *ListChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case listchannel.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case listchannel.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = new(string)
				*_m.MessageID = value.String
			}
		case listchannel.FieldListTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field list_title", values[i])
			} else if value.Valid {
				_m.ListTitle = value.String
			}
		case listchannel.FieldOperationLogThreadID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_log_thread_id", values[i])
			} else if value.Valid {
				_m.OperationLogThreadID = new(string)
				*_m.OperationLogThreadID = value.String
			}
		case listchannel.FieldDefaultCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_category", values[i])
			} else if value.Valid {
				_m.DefaultCategory = value.String
			}
		case listchannel.FieldEditVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field edit_version", values[i])
			} else if value.Valid {
				_m.EditVersion = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ListChannel.
// This includes values selected through modifiers, order, etc.
func (_m *ListChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ListChannel.
// Note that you need to call ListChannel.Unwrap() before calling this method if this ListChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ListChannel) Update() *ListChannelUpdateOne {
	return NewListChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ListChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ListChannel) Unwrap() *ListChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ListChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ListChannel) String() string {
	var builder strings.Builder
	builder.WriteString("ListChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.MessageID; v != nil {
		builder.WriteString("message_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("list_title=")
	builder.WriteString(_m.ListTitle)
	builder.WriteString(", ")
	if v := _m.OperationLogThreadID; v != nil {
		builder.WriteString("operation_log_thread_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("default_category=")
	builder.WriteString(_m.DefaultCategory)
	builder.WriteString(", ")
	builder.WriteString("edit_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.EditVersion))
	builder.WriteByte(')')
	return builder.String()
}

// ListChannels is a parsable slice of ListChannel.
type ListChannels []*ListChannel
