// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/nurserymenu"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// NurseryMenuUpdate is the builder for updating NurseryMenu entities.
type NurseryMenuUpdate struct {
	config
	hooks    []Hook
	mutation *NurseryMenuMutation
}

// Where appends a list predicates to the NurseryMenuUpdate builder.
func (_u *NurseryMenuUpdate) Where(ps ...predicate.NurseryMenu) *NurseryMenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMenuDate sets the "menu_date" field.
func (_u *NurseryMenuUpdate) SetMenuDate(v time.Time) *NurseryMenuUpdate {
	_u.mutation.SetMenuDate(v)
	return _u
}

// SetNillableMenuDate sets the "menu_date" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableMenuDate(v *time.Time) *NurseryMenuUpdate {
	if v != nil {
		_u.SetMenuDate(*v)
	}
	return _u
}

// SetLunch sets the "lunch" field.
func (_u *NurseryMenuUpdate) SetLunch(v string) *NurseryMenuUpdate {
	_u.mutation.SetLunch(v)
	return _u
}

// SetNillableLunch sets the "lunch" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableLunch(v *string) *NurseryMenuUpdate {
	if v != nil {
		_u.SetLunch(*v)
	}
	return _u
}

// SetSnack sets the "snack" field.
func (_u *NurseryMenuUpdate) SetSnack(v string) *NurseryMenuUpdate {
	_u.mutation.SetSnack(v)
	return _u
}

// SetNillableSnack sets the "snack" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableSnack(v *string) *NurseryMenuUpdate {
	if v != nil {
		_u.SetSnack(*v)
	}
	return _u
}

// SetLunchIngredients sets the "lunch_ingredients" field.
func (_u *NurseryMenuUpdate) SetLunchIngredients(v string) *NurseryMenuUpdate {
	_u.mutation.SetLunchIngredients(v)
	return _u
}

// SetNillableLunchIngredients sets the "lunch_ingredients" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableLunchIngredients(v *string) *NurseryMenuUpdate {
	if v != nil {
		_u.SetLunchIngredients(*v)
	}
	return _u
}

// SetSnackIngredients sets the "snack_ingredients" field.
func (_u *NurseryMenuUpdate) SetSnackIngredients(v string) *NurseryMenuUpdate {
	_u.mutation.SetSnackIngredients(v)
	return _u
}

// SetNillableSnackIngredients sets the "snack_ingredients" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableSnackIngredients(v *string) *NurseryMenuUpdate {
	if v != nil {
		_u.SetSnackIngredients(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NurseryMenuUpdate) SetCreatedAt(v time.Time) *NurseryMenuUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableCreatedAt(v *time.Time) *NurseryMenuUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NurseryMenuUpdate) SetUpdatedAt(v time.Time) *NurseryMenuUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NurseryMenuUpdate) SetNillableUpdatedAt(v *time.Time) *NurseryMenuUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the NurseryMenuMutation object of the builder.
func (_u *NurseryMenuUpdate) Mutation() *NurseryMenuMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NurseryMenuUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NurseryMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NurseryMenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NurseryMenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NurseryMenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(nurserymenu.Table, nurserymenu.Columns, sqlgraph.NewFieldSpec(nurserymenu.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MenuDate(); ok {
		_spec.SetField(nurserymenu.FieldMenuDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Lunch(); ok {
		_spec.SetField(nurserymenu.FieldLunch, field.TypeString, value)
	}
	if value, ok := _u.mutation.Snack(); ok {
		_spec.SetField(nurserymenu.FieldSnack, field.TypeString, value)
	}
	if value, ok := _u.mutation.LunchIngredients(); ok {
		_spec.SetField(nurserymenu.FieldLunchIngredients, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnackIngredients(); ok {
		_spec.SetField(nurserymenu.FieldSnackIngredients, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(nurserymenu.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nurserymenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nurserymenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NurseryMenuUpdateOne is the builder for updating a single NurseryMenu entity.
type NurseryMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NurseryMenuMutation
}

// SetMenuDate sets the "menu_date" field.
func (_u *NurseryMenuUpdateOne) SetMenuDate(v time.Time) *NurseryMenuUpdateOne {
	_u.mutation.SetMenuDate(v)
	return _u
}

// SetNillableMenuDate sets the "menu_date" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableMenuDate(v *time.Time) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetMenuDate(*v)
	}
	return _u
}

// SetLunch sets the "lunch" field.
func (_u *NurseryMenuUpdateOne) SetLunch(v string) *NurseryMenuUpdateOne {
	_u.mutation.SetLunch(v)
	return _u
}

// SetNillableLunch sets the "lunch" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableLunch(v *string) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetLunch(*v)
	}
	return _u
}

// SetSnack sets the "snack" field.
func (_u *NurseryMenuUpdateOne) SetSnack(v string) *NurseryMenuUpdateOne {
	_u.mutation.SetSnack(v)
	return _u
}

// SetNillableSnack sets the "snack" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableSnack(v *string) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetSnack(*v)
	}
	return _u
}

// SetLunchIngredients sets the "lunch_ingredients" field.
func (_u *NurseryMenuUpdateOne) SetLunchIngredients(v string) *NurseryMenuUpdateOne {
	_u.mutation.SetLunchIngredients(v)
	return _u
}

// SetNillableLunchIngredients sets the "lunch_ingredients" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableLunchIngredients(v *string) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetLunchIngredients(*v)
	}
	return _u
}

// SetSnackIngredients sets the "snack_ingredients" field.
func (_u *NurseryMenuUpdateOne) SetSnackIngredients(v string) *NurseryMenuUpdateOne {
	_u.mutation.SetSnackIngredients(v)
	return _u
}

// SetNillableSnackIngredients sets the "snack_ingredients" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableSnackIngredients(v *string) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetSnackIngredients(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NurseryMenuUpdateOne) SetCreatedAt(v time.Time) *NurseryMenuUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableCreatedAt(v *time.Time) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NurseryMenuUpdateOne) SetUpdatedAt(v time.Time) *NurseryMenuUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NurseryMenuUpdateOne) SetNillableUpdatedAt(v *time.Time) *NurseryMenuUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the NurseryMenuMutation object of the builder.
func (_u *NurseryMenuUpdateOne) Mutation() *NurseryMenuMutation {
	return _u.mutation
}

// Where appends a list predicates to the NurseryMenuUpdate builder.
func (_u *NurseryMenuUpdateOne) Where(ps ...predicate.NurseryMenu) *NurseryMenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NurseryMenuUpdateOne) Select(field string, fields ...string) *NurseryMenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NurseryMenu entity.
func (_u *NurseryMenuUpdateOne) Save(ctx context.Context) (*NurseryMenu, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NurseryMenuUpdateOne) SaveX(ctx context.Context) *NurseryMenu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NurseryMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NurseryMenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NurseryMenuUpdateOne) sqlSave(ctx context.Context) (_node *NurseryMenu, err error) {
	_spec := sqlgraph.NewUpdateSpec(nurserymenu.Table, nurserymenu.Columns, sqlgraph.NewFieldSpec(nurserymenu.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NurseryMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nurserymenu.FieldID)
		for _, f := range fields {
			if !nurserymenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nurserymenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MenuDate(); ok {
		_spec.SetField(nurserymenu.FieldMenuDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Lunch(); ok {
		_spec.SetField(nurserymenu.FieldLunch, field.TypeString, value)
	}
	if value, ok := _u.mutation.Snack(); ok {
		_spec.SetField(nurserymenu.FieldSnack, field.TypeString, value)
	}
	if value, ok := _u.mutation.LunchIngredients(); ok {
		_spec.SetField(nurserymenu.FieldLunchIngredients, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnackIngredients(); ok {
		_spec.SetField(nurserymenu.FieldSnackIngredients, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(nurserymenu.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(nurserymenu.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &NurseryMenu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nurserymenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
