// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/nurserymenu"
)

// NurseryMenuCreate is the builder for creating a NurseryMenu entity.
type NurseryMenuCreate struct {
	config
	mutation *NurseryMenuMutation
	hooks    []Hook
}

// SetMenuDate sets the "menu_date" field.
func (_c *NurseryMenuCreate) SetMenuDate(v time.Time) *NurseryMenuCreate {
	_c.mutation.SetMenuDate(v)
	return _c
}

// SetLunch sets the "lunch" field.
func (_c *NurseryMenuCreate) SetLunch(v string) *NurseryMenuCreate {
	_c.mutation.SetLunch(v)
	return _c
}

// SetNillableLunch sets the "lunch" field if the given value is not nil.
func (_c *NurseryMenuCreate) SetNillableLunch(v *string) *NurseryMenuCreate {
	if v != nil {
		_c.SetLunch(*v)
	}
	return _c
}

// SetSnack sets the "snack" field.
func (_c *NurseryMenuCreate) SetSnack(v string) *NurseryMenuCreate {
	_c.mutation.SetSnack(v)
	return _c
}

// SetNillableSnack sets the "snack" field if the given value is not nil.
func (_c *NurseryMenuCreate) SetNillableSnack(v *string) *NurseryMenuCreate {
	if v != nil {
		_c.SetSnack(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NurseryMenuCreate) SetCreatedAt(v time.Time) *NurseryMenuCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NurseryMenuCreate) SetUpdatedAt(v time.Time) *NurseryMenuCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NurseryMenuCreate) SetID(v uuid.UUID) *NurseryMenuCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NurseryMenuMutation object of the builder.
func (_c *NurseryMenuCreate) Mutation() *NurseryMenuMutation {
	return _c.mutation
}

// Save creates the NurseryMenu in the database.
func (_c *NurseryMenuCreate) Save(ctx context.Context) (*NurseryMenu, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NurseryMenuCreate) SaveX(ctx context.Context) *NurseryMenu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NurseryMenuCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NurseryMenuCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NurseryMenuCreate) defaults() {
	if _, ok := _c.mutation.Lunch(); !ok {
		v := nurserymenu.DefaultLunch
		_c.mutation.SetLunch(v)
	}
	if _, ok := _c.mutation.Snack(); !ok {
		v := nurserymenu.DefaultSnack
		_c.mutation.SetSnack(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NurseryMenuCreate) check() error {
	if _, ok := _c.mutation.MenuDate(); !ok {
		return &ValidationError{Name: "menu_date", err: errors.New(`ent: missing required field "NurseryMenu.menu_date"`)}
	}
	if _, ok := _c.mutation.Lunch(); !ok {
		return &ValidationError{Name: "lunch", err: errors.New(`ent: missing required field "NurseryMenu.lunch"`)}
	}
	if _, ok := _c.mutation.Snack(); !ok {
		return &ValidationError{Name: "snack", err: errors.New(`ent: missing required field "NurseryMenu.snack"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NurseryMenu.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NurseryMenu.updated_at"`)}
	}
	return nil
}

func (_c *NurseryMenuCreate) sqlSave(ctx context.Context) (*NurseryMenu, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NurseryMenuCreate) createSpec() (*NurseryMenu, *sqlgraph.CreateSpec) {
	var (
		_node = &NurseryMenu{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nurserymenu.Table, sqlgraph.NewFieldSpec(nurserymenu.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MenuDate(); ok {
		_spec.SetField(nurserymenu.FieldMenuDate, field.TypeTime, value)
		_node.MenuDate = value
	}
	if value, ok := _c.mutation.Lunch(); ok {
		_spec.SetField(nurserymenu.FieldLunch, field.TypeString, value)
		_node.Lunch = value
	}
	if value, ok := _c.mutation.Snack(); ok {
		_spec.SetField(nurserymenu.FieldSnack, field.TypeString, value)
		_node.Snack = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(nurserymenu.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(nurserymenu.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NurseryMenuCreateBulk is the builder for creating many NurseryMenu entities in bulk.
type NurseryMenuCreateBulk struct {
	config
	err      error
	builders []*NurseryMenuCreate
}

// Save creates the NurseryMenu entities in the database.
func (_c *NurseryMenuCreateBulk) Save(ctx context.Context) ([]*NurseryMenu, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NurseryMenu, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NurseryMenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NurseryMenuCreateBulk) SaveX(ctx context.Context) []*NurseryMenu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NurseryMenuCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NurseryMenuCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
