// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/nurserymenusetting"
)

// NurseryMenuSettingCreate is the builder for creating a NurseryMenuSetting entity.
type NurseryMenuSettingCreate struct {
	config
	mutation *NurseryMenuSettingMutation
	hooks    []Hook
}

// SetChannelID sets the "channel_id" field.
func (_c *NurseryMenuSettingCreate) SetChannelID(v string) *NurseryMenuSettingCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NurseryMenuSettingCreate) SetUpdatedAt(v time.Time) *NurseryMenuSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NurseryMenuSettingCreate) SetID(v string) *NurseryMenuSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NurseryMenuSettingMutation object of the builder.
func (_c *NurseryMenuSettingCreate) Mutation() *NurseryMenuSettingMutation {
	return _c.mutation
}

// Save creates the NurseryMenuSetting in the database.
func (_c *NurseryMenuSettingCreate) Save(ctx context.Context) (*NurseryMenuSetting, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NurseryMenuSettingCreate) SaveX(ctx context.Context) *NurseryMenuSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NurseryMenuSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NurseryMenuSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NurseryMenuSettingCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "NurseryMenuSetting.channel_id"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NurseryMenuSetting.updated_at"`)}
	}
	return nil
}

func (_c *NurseryMenuSettingCreate) sqlSave(ctx context.Context) (*NurseryMenuSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NurseryMenuSetting.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NurseryMenuSettingCreate) createSpec() (*NurseryMenuSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &NurseryMenuSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nurserymenusetting.Table, sqlgraph.NewFieldSpec(nurserymenusetting.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(nurserymenusetting.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(nurserymenusetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NurseryMenuSettingCreateBulk is the builder for creating many NurseryMenuSetting entities in bulk.
type NurseryMenuSettingCreateBulk struct {
	config
	err      error
	builders []*NurseryMenuSettingCreate
}

// Save creates the NurseryMenuSetting entities in the database.
func (_c *NurseryMenuSettingCreateBulk) Save(ctx context.Context) ([]*NurseryMenuSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NurseryMenuSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NurseryMenuSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NurseryMenuSettingCreateBulk) SaveX(ctx context.Context) []*NurseryMenuSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NurseryMenuSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NurseryMenuSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
