// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/nurserymenu"
)

// NurseryMenu is the model entity for the NurseryMenu schema.
type NurseryMenu struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// MenuDate holds the value of the "menu_date" field.
	MenuDate time.Time `json:"menu_date,omitempty"`
	// Lunch holds the value of the "lunch" field.
	Lunch string `json:"lunch,omitempty"`
	// Snack holds the value of the "snack" field.
	Snack string `json:"snack,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NurseryMenu) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nurserymenu.FieldLunch, nurserymenu.FieldSnack:
			values[i] = new(sql.NullString)
		case nurserymenu.FieldMenuDate, nurserymenu.FieldCreatedAt, nurserymenu.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case nurserymenu.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NurseryMenu fields.
func (_m *NurseryMenu) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nurserymenu.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case nurserymenu.FieldMenuDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field menu_date", values[i])
			} else if value.Valid {
				_m.MenuDate = value.Time
			}
		case nurserymenu.FieldLunch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lunch", values[i])
			} else if value.Valid {
				_m.Lunch = value.String
			}
		case nurserymenu.FieldSnack:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snack", values[i])
			} else if value.Valid {
				_m.Snack = value.String
			}
		case nurserymenu.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nurserymenu.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NurseryMenu.
// This includes values selected through modifiers, order, etc.
func (_m *NurseryMenu) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NurseryMenu.
// Note that you need to call NurseryMenu.Unwrap() before calling this method if this NurseryMenu
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NurseryMenu) Update() *NurseryMenuUpdateOne {
	return NewNurseryMenuClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NurseryMenu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NurseryMenu) Unwrap() *NurseryMenu {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NurseryMenu is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NurseryMenu) String() string {
	var builder strings.Builder
	builder.WriteString("NurseryMenu(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("menu_date=")
	builder.WriteString(_m.MenuDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("lunch=")
	builder.WriteString(_m.Lunch)
	builder.WriteString(", ")
	builder.WriteString("snack=")
	builder.WriteString(_m.Snack)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NurseryMenus is a parsable slice of NurseryMenu.
type NurseryMenus []*NurseryMenu
