// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/operationrecord"
)

// OperationRecord is the model entity for the OperationRecord schema.
type OperationRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID string `json:"channel_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID string `json:"actor_id,omitempty"`
	// OperationKind holds the value of the "operation_kind" field.
	OperationKind string `json:"operation_kind,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Facts holds the value of the "facts" field.
	Facts jsontext.Value `json:"facts,omitempty"`
	// InteractionID holds the value of the "interaction_id" field.
	InteractionID *string `json:"interaction_id,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OperationRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case operationrecord.FieldFacts:
			values[i] = new([]byte)
		case operationrecord.FieldSuccess:
			values[i] = new(sql.NullBool)
		case operationrecord.FieldChannelID, operationrecord.FieldActorID, operationrecord.FieldOperationKind, operationrecord.FieldInteractionID:
			values[i] = new(sql.NullString)
		case operationrecord.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		case operationrecord.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OperationRecord fields.
func (_m *OperationRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case operationrecord.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case operationrecord.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = value.String
			}
		case operationrecord.FieldActorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = value.String
			}
		case operationrecord.FieldOperationKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_kind", values[i])
			} else if value.Valid {
				_m.OperationKind = value.String
			}
		case operationrecord.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case operationrecord.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case operationrecord.FieldFacts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field facts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Facts); err != nil {
					return fmt.Errorf("unmarshal field facts: %w", err)
				}
			}
		case operationrecord.FieldInteractionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interaction_id", values[i])
			} else if value.Valid {
				_m.InteractionID = new(string)
				*_m.InteractionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OperationRecord.
// This includes values selected through modifiers, order, etc.
func (_m *OperationRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OperationRecord.
// Note that you need to call OperationRecord.Unwrap() before calling this method if this OperationRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OperationRecord) Update() *OperationRecordUpdateOne {
	return NewOperationRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OperationRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OperationRecord) Unwrap() *OperationRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OperationRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OperationRecord) String() string {
	var builder strings.Builder
	builder.WriteString("OperationRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel_id=")
	builder.WriteString(_m.ChannelID)
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(_m.ActorID)
	builder.WriteString(", ")
	builder.WriteString("operation_kind=")
	builder.WriteString(_m.OperationKind)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("facts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Facts))
	builder.WriteString(", ")
	if v := _m.InteractionID; v != nil {
		builder.WriteString("interaction_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// OperationRecords is a parsable slice of OperationRecord.
type OperationRecords []*OperationRecord
