// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/operationrecord"
)

// OperationRecordCreate is the builder for creating a OperationRecord entity.
type OperationRecordCreate struct {
	config
	mutation *OperationRecordMutation
	hooks    []Hook
}

// SetChannelID sets the "channel_id" field.
func (_c *OperationRecordCreate) SetChannelID(v string) *OperationRecordCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *OperationRecordCreate) SetActorID(v string) *OperationRecordCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetOperationKind sets the "operation_kind" field.
func (_c *OperationRecordCreate) SetOperationKind(v string) *OperationRecordCreate {
	_c.mutation.SetOperationKind(v)
	return _c
}

// SetSuccess sets the "success" field.
func (_c *OperationRecordCreate) SetSuccess(v bool) *OperationRecordCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *OperationRecordCreate) SetOccurredAt(v time.Time) *OperationRecordCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetFacts sets the "facts" field.
func (_c *OperationRecordCreate) SetFacts(v jsontext.Value) *OperationRecordCreate {
	_c.mutation.SetFacts(v)
	return _c
}

// SetInteractionID sets the "interaction_id" field.
func (_c *OperationRecordCreate) SetInteractionID(v string) *OperationRecordCreate {
	_c.mutation.SetInteractionID(v)
	return _c
}

// SetNillableInteractionID sets the "interaction_id" field if the given value is not nil.
func (_c *OperationRecordCreate) SetNillableInteractionID(v *string) *OperationRecordCreate {
	if v != nil {
		_c.SetInteractionID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperationRecordCreate) SetID(v uuid.UUID) *OperationRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OperationRecordMutation object of the builder.
func (_c *OperationRecordCreate) Mutation() *OperationRecordMutation {
	return _c.mutation
}

// Save creates the OperationRecord in the database.
func (_c *OperationRecordCreate) Save(ctx context.Context) (*OperationRecord, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperationRecordCreate) SaveX(ctx context.Context) *OperationRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperationRecordCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "OperationRecord.channel_id"`)}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "OperationRecord.actor_id"`)}
	}
	if _, ok := _c.mutation.OperationKind(); !ok {
		return &ValidationError{Name: "operation_kind", err: errors.New(`ent: missing required field "OperationRecord.operation_kind"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "OperationRecord.success"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "OperationRecord.occurred_at"`)}
	}
	if _, ok := _c.mutation.Facts(); !ok {
		return &ValidationError{Name: "facts", err: errors.New(`ent: missing required field "OperationRecord.facts"`)}
	}
	return nil
}

func (_c *OperationRecordCreate) sqlSave(ctx context.Context) (*OperationRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperationRecordCreate) createSpec() (*OperationRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &OperationRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operationrecord.Table, sqlgraph.NewFieldSpec(operationrecord.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(operationrecord.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(operationrecord.FieldActorID, field.TypeString, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.OperationKind(); ok {
		_spec.SetField(operationrecord.FieldOperationKind, field.TypeString, value)
		_node.OperationKind = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(operationrecord.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(operationrecord.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.Facts(); ok {
		_spec.SetField(operationrecord.FieldFacts, field.TypeJSON, value)
		_node.Facts = value
	}
	if value, ok := _c.mutation.InteractionID(); ok {
		_spec.SetField(operationrecord.FieldInteractionID, field.TypeString, value)
		_node.InteractionID = &value
	}
	return _node, _spec
}

// OperationRecordCreateBulk is the builder for creating many OperationRecord entities in bulk.
type OperationRecordCreateBulk struct {
	config
	err      error
	builders []*OperationRecordCreate
}

// Save creates the OperationRecord entities in the database.
func (_c *OperationRecordCreateBulk) Save(ctx context.Context) ([]*OperationRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OperationRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperationRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperationRecordCreateBulk) SaveX(ctx context.Context) []*OperationRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
