// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/operationrecord"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// OperationRecordDelete is the builder for deleting a OperationRecord entity.
type OperationRecordDelete struct {
	config
	hooks    []Hook
	mutation *OperationRecordMutation
}

// Where appends a list predicates to the OperationRecordDelete builder.
func (_d *OperationRecordDelete) Where(ps ...predicate.OperationRecord) *OperationRecordDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OperationRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OperationRecordDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OperationRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(operationrecord.Table, sqlgraph.NewFieldSpec(operationrecord.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OperationRecordDeleteOne is the builder for deleting a single OperationRecord entity.
type OperationRecordDeleteOne struct {
	_d *OperationRecordDelete
}

// Where appends a list predicates to the OperationRecordDelete builder.
func (_d *OperationRecordDeleteOne) Where(ps ...predicate.OperationRecord) *OperationRecordDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OperationRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{operationrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OperationRecordDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
