// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/outputtask"
)

// OutputTaskCreate is the builder for creating a OutputTask entity.
type OutputTaskCreate struct {
	config
	mutation *OutputTaskMutation
	hooks    []Hook
}

// SetChannelID sets the "channel_id" field.
func (_c *OutputTaskCreate) SetChannelID(v string) *OutputTaskCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *OutputTaskCreate) SetKind(v string) *OutputTaskCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *OutputTaskCreate) SetTargetID(v string) *OutputTaskCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetOperationID sets the "operation_id" field.
func (_c *OutputTaskCreate) SetOperationID(v uuid.UUID) *OutputTaskCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_c *OutputTaskCreate) SetNillableOperationID(v *uuid.UUID) *OutputTaskCreate {
	if v != nil {
		_c.SetOperationID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *OutputTaskCreate) SetPayload(v jsontext.Value) *OutputTaskCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetDestinationKey sets the "destination_key" field.
func (_c *OutputTaskCreate) SetDestinationKey(v string) *OutputTaskCreate {
	_c.mutation.SetDestinationKey(v)
	return _c
}

// SetDedupKey sets the "dedup_key" field.
func (_c *OutputTaskCreate) SetDedupKey(v string) *OutputTaskCreate {
	_c.mutation.SetDedupKey(v)
	return _c
}

// SetNillableDedupKey sets the "dedup_key" field if the given value is not nil.
func (_c *OutputTaskCreate) SetNillableDedupKey(v *string) *OutputTaskCreate {
	if v != nil {
		_c.SetDedupKey(*v)
	}
	return _c
}

// SetOutputOrder sets the "output_order" field.
func (_c *OutputTaskCreate) SetOutputOrder(v int64) *OutputTaskCreate {
	_c.mutation.SetOutputOrder(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OutputTaskCreate) SetState(v string) *OutputTaskCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *OutputTaskCreate) SetAttempts(v int) *OutputTaskCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *OutputTaskCreate) SetNillableAttempts(v *int) *OutputTaskCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *OutputTaskCreate) SetAvailableAt(v time.Time) *OutputTaskCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetExecutor sets the "executor" field.
func (_c *OutputTaskCreate) SetExecutor(v string) *OutputTaskCreate {
	_c.mutation.SetExecutor(v)
	return _c
}

// SetNillableExecutor sets the "executor" field if the given value is not nil.
func (_c *OutputTaskCreate) SetNillableExecutor(v *string) *OutputTaskCreate {
	if v != nil {
		_c.SetExecutor(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *OutputTaskCreate) SetLastError(v string) *OutputTaskCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *OutputTaskCreate) SetNillableLastError(v *string) *OutputTaskCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutputTaskCreate) SetCreatedAt(v time.Time) *OutputTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OutputTaskCreate) SetUpdatedAt(v time.Time) *OutputTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OutputTaskCreate) SetID(v uuid.UUID) *OutputTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OutputTaskMutation object of the builder.
func (_c *OutputTaskCreate) Mutation() *OutputTaskMutation {
	return _c.mutation
}

// Save creates the OutputTask in the database.
func (_c *OutputTaskCreate) Save(ctx context.Context) (*OutputTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutputTaskCreate) SaveX(ctx context.Context) *OutputTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutputTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutputTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutputTaskCreate) defaults() {
	if _, ok := _c.mutation.Attempts(); !ok {
		v := outputtask.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.Executor(); !ok {
		v := outputtask.DefaultExecutor
		_c.mutation.SetExecutor(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := outputtask.DefaultLastError
		_c.mutation.SetLastError(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutputTaskCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "OutputTask.channel_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "OutputTask.kind"`)}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "OutputTask.target_id"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "OutputTask.payload"`)}
	}
	if _, ok := _c.mutation.DestinationKey(); !ok {
		return &ValidationError{Name: "destination_key", err: errors.New(`ent: missing required field "OutputTask.destination_key"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "OutputTask.state"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "OutputTask.attempts"`)}
	}
	if v, ok := _c.mutation.Attempts(); ok {
		if err := outputtask.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "OutputTask.attempts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "OutputTask.available_at"`)}
	}
	if _, ok := _c.mutation.Executor(); !ok {
		return &ValidationError{Name: "executor", err: errors.New(`ent: missing required field "OutputTask.executor"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "OutputTask.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OutputTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OutputTask.updated_at"`)}
	}
	return nil
}

func (_c *OutputTaskCreate) sqlSave(ctx context.Context) (*OutputTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutputTaskCreate) createSpec() (*OutputTask, *sqlgraph.CreateSpec) {
	var (
		_node = &OutputTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outputtask.Table, sqlgraph.NewFieldSpec(outputtask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(outputtask.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(outputtask.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(outputtask.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(outputtask.FieldOperationID, field.TypeUUID, value)
		_node.OperationID = &value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(outputtask.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.DestinationKey(); ok {
		_spec.SetField(outputtask.FieldDestinationKey, field.TypeString, value)
		_node.DestinationKey = value
	}
	if value, ok := _c.mutation.DedupKey(); ok {
		_spec.SetField(outputtask.FieldDedupKey, field.TypeString, value)
		_node.DedupKey = &value
	}
	if value, ok := _c.mutation.OutputOrder(); ok {
		_spec.SetField(outputtask.FieldOutputOrder, field.TypeInt64, value)
		_node.OutputOrder = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(outputtask.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(outputtask.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(outputtask.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = value
	}
	if value, ok := _c.mutation.Executor(); ok {
		_spec.SetField(outputtask.FieldExecutor, field.TypeString, value)
		_node.Executor = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(outputtask.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outputtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(outputtask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OutputTaskCreateBulk is the builder for creating many OutputTask entities in bulk.
type OutputTaskCreateBulk struct {
	config
	err      error
	builders []*OutputTaskCreate
}

// Save creates the OutputTask entities in the database.
func (_c *OutputTaskCreateBulk) Save(ctx context.Context) ([]*OutputTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OutputTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutputTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutputTaskCreateBulk) SaveX(ctx context.Context) []*OutputTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutputTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutputTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
