// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/outputdispatch"
)

// OutputDispatch is the model entity for the OutputDispatch schema.
type OutputDispatch struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// Nonce holds the value of the "nonce" field.
	Nonce string `json:"nonce,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome string `json:"outcome,omitempty"`
	// DiscordMessageID holds the value of the "discord_message_id" field.
	DiscordMessageID string `json:"discord_message_id,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutputDispatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outputdispatch.FieldAttempt:
			values[i] = new(sql.NullInt64)
		case outputdispatch.FieldNonce, outputdispatch.FieldOutcome, outputdispatch.FieldDiscordMessageID:
			values[i] = new(sql.NullString)
		case outputdispatch.FieldStartedAt, outputdispatch.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		case outputdispatch.FieldID, outputdispatch.FieldTaskID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutputDispatch fields.
func (_m *OutputDispatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outputdispatch.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case outputdispatch.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case outputdispatch.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int(value.Int64)
			}
		case outputdispatch.FieldNonce:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nonce", values[i])
			} else if value.Valid {
				_m.Nonce = value.String
			}
		case outputdispatch.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case outputdispatch.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case outputdispatch.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = value.String
			}
		case outputdispatch.FieldDiscordMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discord_message_id", values[i])
			} else if value.Valid {
				_m.DiscordMessageID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutputDispatch.
// This includes values selected through modifiers, order, etc.
func (_m *OutputDispatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OutputDispatch.
// Note that you need to call OutputDispatch.Unwrap() before calling this method if this OutputDispatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OutputDispatch) Update() *OutputDispatchUpdateOne {
	return NewOutputDispatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OutputDispatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OutputDispatch) Unwrap() *OutputDispatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutputDispatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OutputDispatch) String() string {
	var builder strings.Builder
	builder.WriteString("OutputDispatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteString(", ")
	builder.WriteString("nonce=")
	builder.WriteString(_m.Nonce)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(_m.Outcome)
	builder.WriteString(", ")
	builder.WriteString("discord_message_id=")
	builder.WriteString(_m.DiscordMessageID)
	builder.WriteByte(')')
	return builder.String()
}

// OutputDispatches is a parsable slice of OutputDispatch.
type OutputDispatches []*OutputDispatch
