// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/remindtaskinventoryitem"
)

// RemindTaskInventoryItemCreate is the builder for creating a RemindTaskInventoryItem entity.
type RemindTaskInventoryItemCreate struct {
	config
	mutation *RemindTaskInventoryItemMutation
	hooks    []Hook
}

// SetTaskChannelID sets the "task_channel_id" field.
func (_c *RemindTaskInventoryItemCreate) SetTaskChannelID(v string) *RemindTaskInventoryItemCreate {
	_c.mutation.SetTaskChannelID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *RemindTaskInventoryItemCreate) SetTaskID(v string) *RemindTaskInventoryItemCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetInventoryChannelID sets the "inventory_channel_id" field.
func (_c *RemindTaskInventoryItemCreate) SetInventoryChannelID(v string) *RemindTaskInventoryItemCreate {
	_c.mutation.SetInventoryChannelID(v)
	return _c
}

// SetInventoryID sets the "inventory_id" field.
func (_c *RemindTaskInventoryItemCreate) SetInventoryID(v string) *RemindTaskInventoryItemCreate {
	_c.mutation.SetInventoryID(v)
	return _c
}

// SetConsume sets the "consume" field.
func (_c *RemindTaskInventoryItemCreate) SetConsume(v string) *RemindTaskInventoryItemCreate {
	_c.mutation.SetConsume(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *RemindTaskInventoryItemCreate) SetPosition(v int) *RemindTaskInventoryItemCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RemindTaskInventoryItemCreate) SetID(v uuid.UUID) *RemindTaskInventoryItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RemindTaskInventoryItemMutation object of the builder.
func (_c *RemindTaskInventoryItemCreate) Mutation() *RemindTaskInventoryItemMutation {
	return _c.mutation
}

// Save creates the RemindTaskInventoryItem in the database.
func (_c *RemindTaskInventoryItemCreate) Save(ctx context.Context) (*RemindTaskInventoryItem, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RemindTaskInventoryItemCreate) SaveX(ctx context.Context) *RemindTaskInventoryItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemindTaskInventoryItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemindTaskInventoryItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RemindTaskInventoryItemCreate) check() error {
	if _, ok := _c.mutation.TaskChannelID(); !ok {
		return &ValidationError{Name: "task_channel_id", err: errors.New(`ent: missing required field "RemindTaskInventoryItem.task_channel_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "RemindTaskInventoryItem.task_id"`)}
	}
	if _, ok := _c.mutation.InventoryChannelID(); !ok {
		return &ValidationError{Name: "inventory_channel_id", err: errors.New(`ent: missing required field "RemindTaskInventoryItem.inventory_channel_id"`)}
	}
	if _, ok := _c.mutation.InventoryID(); !ok {
		return &ValidationError{Name: "inventory_id", err: errors.New(`ent: missing required field "RemindTaskInventoryItem.inventory_id"`)}
	}
	if _, ok := _c.mutation.Consume(); !ok {
		return &ValidationError{Name: "consume", err: errors.New(`ent: missing required field "RemindTaskInventoryItem.consume"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "RemindTaskInventoryItem.position"`)}
	}
	return nil
}

func (_c *RemindTaskInventoryItemCreate) sqlSave(ctx context.Context) (*RemindTaskInventoryItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RemindTaskInventoryItemCreate) createSpec() (*RemindTaskInventoryItem, *sqlgraph.CreateSpec) {
	var (
		_node = &RemindTaskInventoryItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(remindtaskinventoryitem.Table, sqlgraph.NewFieldSpec(remindtaskinventoryitem.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TaskChannelID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldTaskChannelID, field.TypeString, value)
		_node.TaskChannelID = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.InventoryChannelID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldInventoryChannelID, field.TypeString, value)
		_node.InventoryChannelID = value
	}
	if value, ok := _c.mutation.InventoryID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldInventoryID, field.TypeString, value)
		_node.InventoryID = value
	}
	if value, ok := _c.mutation.Consume(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldConsume, field.TypeString, value)
		_node.Consume = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	return _node, _spec
}

// RemindTaskInventoryItemCreateBulk is the builder for creating many RemindTaskInventoryItem entities in bulk.
type RemindTaskInventoryItemCreateBulk struct {
	config
	err      error
	builders []*RemindTaskInventoryItemCreate
}

// Save creates the RemindTaskInventoryItem entities in the database.
func (_c *RemindTaskInventoryItemCreateBulk) Save(ctx context.Context) ([]*RemindTaskInventoryItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RemindTaskInventoryItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemindTaskInventoryItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RemindTaskInventoryItemCreateBulk) SaveX(ctx context.Context) []*RemindTaskInventoryItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemindTaskInventoryItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemindTaskInventoryItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
