// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/remindtaskinventoryitem"
)

// RemindTaskInventoryItemUpdate is the builder for updating RemindTaskInventoryItem entities.
type RemindTaskInventoryItemUpdate struct {
	config
	hooks    []Hook
	mutation *RemindTaskInventoryItemMutation
}

// Where appends a list predicates to the RemindTaskInventoryItemUpdate builder.
func (_u *RemindTaskInventoryItemUpdate) Where(ps ...predicate.RemindTaskInventoryItem) *RemindTaskInventoryItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskChannelID sets the "task_channel_id" field.
func (_u *RemindTaskInventoryItemUpdate) SetTaskChannelID(v string) *RemindTaskInventoryItemUpdate {
	_u.mutation.SetTaskChannelID(v)
	return _u
}

// SetNillableTaskChannelID sets the "task_channel_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdate) SetNillableTaskChannelID(v *string) *RemindTaskInventoryItemUpdate {
	if v != nil {
		_u.SetTaskChannelID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *RemindTaskInventoryItemUpdate) SetTaskID(v string) *RemindTaskInventoryItemUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdate) SetNillableTaskID(v *string) *RemindTaskInventoryItemUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetInventoryChannelID sets the "inventory_channel_id" field.
func (_u *RemindTaskInventoryItemUpdate) SetInventoryChannelID(v string) *RemindTaskInventoryItemUpdate {
	_u.mutation.SetInventoryChannelID(v)
	return _u
}

// SetNillableInventoryChannelID sets the "inventory_channel_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdate) SetNillableInventoryChannelID(v *string) *RemindTaskInventoryItemUpdate {
	if v != nil {
		_u.SetInventoryChannelID(*v)
	}
	return _u
}

// SetInventoryID sets the "inventory_id" field.
func (_u *RemindTaskInventoryItemUpdate) SetInventoryID(v string) *RemindTaskInventoryItemUpdate {
	_u.mutation.SetInventoryID(v)
	return _u
}

// SetNillableInventoryID sets the "inventory_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdate) SetNillableInventoryID(v *string) *RemindTaskInventoryItemUpdate {
	if v != nil {
		_u.SetInventoryID(*v)
	}
	return _u
}

// SetConsume sets the "consume" field.
func (_u *RemindTaskInventoryItemUpdate) SetConsume(v string) *RemindTaskInventoryItemUpdate {
	_u.mutation.SetConsume(v)
	return _u
}

// SetNillableConsume sets the "consume" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdate) SetNillableConsume(v *string) *RemindTaskInventoryItemUpdate {
	if v != nil {
		_u.SetConsume(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *RemindTaskInventoryItemUpdate) SetPosition(v int) *RemindTaskInventoryItemUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdate) SetNillablePosition(v *int) *RemindTaskInventoryItemUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *RemindTaskInventoryItemUpdate) AddPosition(v int) *RemindTaskInventoryItemUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the RemindTaskInventoryItemMutation object of the builder.
func (_u *RemindTaskInventoryItemUpdate) Mutation() *RemindTaskInventoryItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RemindTaskInventoryItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RemindTaskInventoryItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RemindTaskInventoryItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RemindTaskInventoryItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RemindTaskInventoryItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(remindtaskinventoryitem.Table, remindtaskinventoryitem.Columns, sqlgraph.NewFieldSpec(remindtaskinventoryitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskChannelID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldTaskChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryChannelID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldInventoryChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldInventoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Consume(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldConsume, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(remindtaskinventoryitem.FieldPosition, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remindtaskinventoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RemindTaskInventoryItemUpdateOne is the builder for updating a single RemindTaskInventoryItem entity.
type RemindTaskInventoryItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RemindTaskInventoryItemMutation
}

// SetTaskChannelID sets the "task_channel_id" field.
func (_u *RemindTaskInventoryItemUpdateOne) SetTaskChannelID(v string) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.SetTaskChannelID(v)
	return _u
}

// SetNillableTaskChannelID sets the "task_channel_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdateOne) SetNillableTaskChannelID(v *string) *RemindTaskInventoryItemUpdateOne {
	if v != nil {
		_u.SetTaskChannelID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *RemindTaskInventoryItemUpdateOne) SetTaskID(v string) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdateOne) SetNillableTaskID(v *string) *RemindTaskInventoryItemUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetInventoryChannelID sets the "inventory_channel_id" field.
func (_u *RemindTaskInventoryItemUpdateOne) SetInventoryChannelID(v string) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.SetInventoryChannelID(v)
	return _u
}

// SetNillableInventoryChannelID sets the "inventory_channel_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdateOne) SetNillableInventoryChannelID(v *string) *RemindTaskInventoryItemUpdateOne {
	if v != nil {
		_u.SetInventoryChannelID(*v)
	}
	return _u
}

// SetInventoryID sets the "inventory_id" field.
func (_u *RemindTaskInventoryItemUpdateOne) SetInventoryID(v string) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.SetInventoryID(v)
	return _u
}

// SetNillableInventoryID sets the "inventory_id" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdateOne) SetNillableInventoryID(v *string) *RemindTaskInventoryItemUpdateOne {
	if v != nil {
		_u.SetInventoryID(*v)
	}
	return _u
}

// SetConsume sets the "consume" field.
func (_u *RemindTaskInventoryItemUpdateOne) SetConsume(v string) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.SetConsume(v)
	return _u
}

// SetNillableConsume sets the "consume" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdateOne) SetNillableConsume(v *string) *RemindTaskInventoryItemUpdateOne {
	if v != nil {
		_u.SetConsume(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *RemindTaskInventoryItemUpdateOne) SetPosition(v int) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *RemindTaskInventoryItemUpdateOne) SetNillablePosition(v *int) *RemindTaskInventoryItemUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *RemindTaskInventoryItemUpdateOne) AddPosition(v int) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the RemindTaskInventoryItemMutation object of the builder.
func (_u *RemindTaskInventoryItemUpdateOne) Mutation() *RemindTaskInventoryItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the RemindTaskInventoryItemUpdate builder.
func (_u *RemindTaskInventoryItemUpdateOne) Where(ps ...predicate.RemindTaskInventoryItem) *RemindTaskInventoryItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RemindTaskInventoryItemUpdateOne) Select(field string, fields ...string) *RemindTaskInventoryItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RemindTaskInventoryItem entity.
func (_u *RemindTaskInventoryItemUpdateOne) Save(ctx context.Context) (*RemindTaskInventoryItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RemindTaskInventoryItemUpdateOne) SaveX(ctx context.Context) *RemindTaskInventoryItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RemindTaskInventoryItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RemindTaskInventoryItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RemindTaskInventoryItemUpdateOne) sqlSave(ctx context.Context) (_node *RemindTaskInventoryItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(remindtaskinventoryitem.Table, remindtaskinventoryitem.Columns, sqlgraph.NewFieldSpec(remindtaskinventoryitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RemindTaskInventoryItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, remindtaskinventoryitem.FieldID)
		for _, f := range fields {
			if !remindtaskinventoryitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != remindtaskinventoryitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskChannelID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldTaskChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryChannelID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldInventoryChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryID(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldInventoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Consume(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldConsume, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(remindtaskinventoryitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(remindtaskinventoryitem.FieldPosition, field.TypeInt, value)
	}
	_node = &RemindTaskInventoryItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remindtaskinventoryitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
