// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/remindchannel"
)

// RemindChannelCreate is the builder for creating a RemindChannel entity.
type RemindChannelCreate struct {
	config
	mutation *RemindChannelMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (_c *RemindChannelCreate) SetMessageID(v string) *RemindChannelCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *RemindChannelCreate) SetNillableMessageID(v *string) *RemindChannelCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetListTitle sets the "list_title" field.
func (_c *RemindChannelCreate) SetListTitle(v string) *RemindChannelCreate {
	_c.mutation.SetListTitle(v)
	return _c
}

// SetOperationLogThreadID sets the "operation_log_thread_id" field.
func (_c *RemindChannelCreate) SetOperationLogThreadID(v string) *RemindChannelCreate {
	_c.mutation.SetOperationLogThreadID(v)
	return _c
}

// SetNillableOperationLogThreadID sets the "operation_log_thread_id" field if the given value is not nil.
func (_c *RemindChannelCreate) SetNillableOperationLogThreadID(v *string) *RemindChannelCreate {
	if v != nil {
		_c.SetOperationLogThreadID(*v)
	}
	return _c
}

// SetRemindNoticeThreadID sets the "remind_notice_thread_id" field.
func (_c *RemindChannelCreate) SetRemindNoticeThreadID(v string) *RemindChannelCreate {
	_c.mutation.SetRemindNoticeThreadID(v)
	return _c
}

// SetNillableRemindNoticeThreadID sets the "remind_notice_thread_id" field if the given value is not nil.
func (_c *RemindChannelCreate) SetNillableRemindNoticeThreadID(v *string) *RemindChannelCreate {
	if v != nil {
		_c.SetRemindNoticeThreadID(*v)
	}
	return _c
}

// SetRemindNoticeMessageID sets the "remind_notice_message_id" field.
func (_c *RemindChannelCreate) SetRemindNoticeMessageID(v string) *RemindChannelCreate {
	_c.mutation.SetRemindNoticeMessageID(v)
	return _c
}

// SetNillableRemindNoticeMessageID sets the "remind_notice_message_id" field if the given value is not nil.
func (_c *RemindChannelCreate) SetNillableRemindNoticeMessageID(v *string) *RemindChannelCreate {
	if v != nil {
		_c.SetRemindNoticeMessageID(*v)
	}
	return _c
}

// SetLinkedInventoryChannelID sets the "linked_inventory_channel_id" field.
func (_c *RemindChannelCreate) SetLinkedInventoryChannelID(v string) *RemindChannelCreate {
	_c.mutation.SetLinkedInventoryChannelID(v)
	return _c
}

// SetNillableLinkedInventoryChannelID sets the "linked_inventory_channel_id" field if the given value is not nil.
func (_c *RemindChannelCreate) SetNillableLinkedInventoryChannelID(v *string) *RemindChannelCreate {
	if v != nil {
		_c.SetLinkedInventoryChannelID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RemindChannelCreate) SetID(v string) *RemindChannelCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RemindChannelMutation object of the builder.
func (_c *RemindChannelCreate) Mutation() *RemindChannelMutation {
	return _c.mutation
}

// Save creates the RemindChannel in the database.
func (_c *RemindChannelCreate) Save(ctx context.Context) (*RemindChannel, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RemindChannelCreate) SaveX(ctx context.Context) *RemindChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemindChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemindChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RemindChannelCreate) check() error {
	if _, ok := _c.mutation.ListTitle(); !ok {
		return &ValidationError{Name: "list_title", err: errors.New(`ent: missing required field "RemindChannel.list_title"`)}
	}
	return nil
}

func (_c *RemindChannelCreate) sqlSave(ctx context.Context) (*RemindChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RemindChannel.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RemindChannelCreate) createSpec() (*RemindChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &RemindChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(remindchannel.Table, sqlgraph.NewFieldSpec(remindchannel.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(remindchannel.FieldMessageID, field.TypeString, value)
		_node.MessageID = &value
	}
	if value, ok := _c.mutation.ListTitle(); ok {
		_spec.SetField(remindchannel.FieldListTitle, field.TypeString, value)
		_node.ListTitle = value
	}
	if value, ok := _c.mutation.OperationLogThreadID(); ok {
		_spec.SetField(remindchannel.FieldOperationLogThreadID, field.TypeString, value)
		_node.OperationLogThreadID = &value
	}
	if value, ok := _c.mutation.RemindNoticeThreadID(); ok {
		_spec.SetField(remindchannel.FieldRemindNoticeThreadID, field.TypeString, value)
		_node.RemindNoticeThreadID = &value
	}
	if value, ok := _c.mutation.RemindNoticeMessageID(); ok {
		_spec.SetField(remindchannel.FieldRemindNoticeMessageID, field.TypeString, value)
		_node.RemindNoticeMessageID = &value
	}
	if value, ok := _c.mutation.LinkedInventoryChannelID(); ok {
		_spec.SetField(remindchannel.FieldLinkedInventoryChannelID, field.TypeString, value)
		_node.LinkedInventoryChannelID = &value
	}
	return _node, _spec
}

// RemindChannelCreateBulk is the builder for creating many RemindChannel entities in bulk.
type RemindChannelCreateBulk struct {
	config
	err      error
	builders []*RemindChannelCreate
}

// Save creates the RemindChannel entities in the database.
func (_c *RemindChannelCreateBulk) Save(ctx context.Context) ([]*RemindChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RemindChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemindChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RemindChannelCreateBulk) SaveX(ctx context.Context) []*RemindChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemindChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemindChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
