// Code generated by ent, DO NOT EDIT.

package channeloutputsuspension

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the channeloutputsuspension type in the database.
	Label = "channel_output_suspension"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "channel_id"
	// FieldSuspendedAt holds the string denoting the suspended_at field in the database.
	FieldSuspendedAt = "suspended_at"
	// FieldSuspendedBy holds the string denoting the suspended_by field in the database.
	FieldSuspendedBy = "suspended_by"
	// Table holds the table name of the channeloutputsuspension in the database.
	Table = "channel_output_suspensions"
)

// Columns holds all SQL columns for channeloutputsuspension fields.
var Columns = []string{
	FieldID,
	FieldSuspendedAt,
	FieldSuspendedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ChannelOutputSuspension queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySuspendedAt orders the results by the suspended_at field.
func BySuspendedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuspendedAt, opts...).ToFunc()
}

// BySuspendedBy orders the results by the suspended_by field.
func BySuspendedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuspendedBy, opts...).ToFunc()
}
