// Code generated by ent, DO NOT EDIT.

package channeloutputsuspension

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/yone-k/yone-discord-bot/backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldContainsFold(FieldID, id))
}

// SuspendedAt applies equality check predicate on the "suspended_at" field. It's identical to SuspendedAtEQ.
func SuspendedAt(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEQ(FieldSuspendedAt, v))
}

// SuspendedBy applies equality check predicate on the "suspended_by" field. It's identical to SuspendedByEQ.
func SuspendedBy(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEQ(FieldSuspendedBy, v))
}

// SuspendedAtEQ applies the EQ predicate on the "suspended_at" field.
func SuspendedAtEQ(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEQ(FieldSuspendedAt, v))
}

// SuspendedAtNEQ applies the NEQ predicate on the "suspended_at" field.
func SuspendedAtNEQ(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldNEQ(FieldSuspendedAt, v))
}

// SuspendedAtIn applies the In predicate on the "suspended_at" field.
func SuspendedAtIn(vs ...time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldIn(FieldSuspendedAt, vs...))
}

// SuspendedAtNotIn applies the NotIn predicate on the "suspended_at" field.
func SuspendedAtNotIn(vs ...time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldNotIn(FieldSuspendedAt, vs...))
}

// SuspendedAtGT applies the GT predicate on the "suspended_at" field.
func SuspendedAtGT(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldGT(FieldSuspendedAt, v))
}

// SuspendedAtGTE applies the GTE predicate on the "suspended_at" field.
func SuspendedAtGTE(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldGTE(FieldSuspendedAt, v))
}

// SuspendedAtLT applies the LT predicate on the "suspended_at" field.
func SuspendedAtLT(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldLT(FieldSuspendedAt, v))
}

// SuspendedAtLTE applies the LTE predicate on the "suspended_at" field.
func SuspendedAtLTE(v time.Time) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldLTE(FieldSuspendedAt, v))
}

// SuspendedByEQ applies the EQ predicate on the "suspended_by" field.
func SuspendedByEQ(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEQ(FieldSuspendedBy, v))
}

// SuspendedByNEQ applies the NEQ predicate on the "suspended_by" field.
func SuspendedByNEQ(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldNEQ(FieldSuspendedBy, v))
}

// SuspendedByIn applies the In predicate on the "suspended_by" field.
func SuspendedByIn(vs ...string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldIn(FieldSuspendedBy, vs...))
}

// SuspendedByNotIn applies the NotIn predicate on the "suspended_by" field.
func SuspendedByNotIn(vs ...string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldNotIn(FieldSuspendedBy, vs...))
}

// SuspendedByGT applies the GT predicate on the "suspended_by" field.
func SuspendedByGT(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldGT(FieldSuspendedBy, v))
}

// SuspendedByGTE applies the GTE predicate on the "suspended_by" field.
func SuspendedByGTE(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldGTE(FieldSuspendedBy, v))
}

// SuspendedByLT applies the LT predicate on the "suspended_by" field.
func SuspendedByLT(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldLT(FieldSuspendedBy, v))
}

// SuspendedByLTE applies the LTE predicate on the "suspended_by" field.
func SuspendedByLTE(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldLTE(FieldSuspendedBy, v))
}

// SuspendedByContains applies the Contains predicate on the "suspended_by" field.
func SuspendedByContains(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldContains(FieldSuspendedBy, v))
}

// SuspendedByHasPrefix applies the HasPrefix predicate on the "suspended_by" field.
func SuspendedByHasPrefix(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldHasPrefix(FieldSuspendedBy, v))
}

// SuspendedByHasSuffix applies the HasSuffix predicate on the "suspended_by" field.
func SuspendedByHasSuffix(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldHasSuffix(FieldSuspendedBy, v))
}

// SuspendedByEqualFold applies the EqualFold predicate on the "suspended_by" field.
func SuspendedByEqualFold(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldEqualFold(FieldSuspendedBy, v))
}

// SuspendedByContainsFold applies the ContainsFold predicate on the "suspended_by" field.
func SuspendedByContainsFold(v string) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.FieldContainsFold(FieldSuspendedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelOutputSuspension) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelOutputSuspension) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelOutputSuspension) predicate.ChannelOutputSuspension {
	return predicate.ChannelOutputSuspension(sql.NotPredicates(p))
}
